export const approvalRequiredRegistrationModuleManifest = {
  seed_id: 'seed_6c_104_approval_required_registration',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.approval_required_registration',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Approval-required registration workflow',
  proposed_model_name: 'Phase6CApprovalRequiredRegistration',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-008', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'registration_ref',
    'attendee_ref',
    'approval_policy_ref',
    'required_approval_count',
    'approval_action_evidence_refs',
    'approval_required_registration_runtime_digest',
  ],
  evidence_artifacts: [
    'approval_required_registration_runtime_receipt',
    'approval_required_registration_validation_result',
    'approval_required_registration_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'approval_mutation',
    'registration_creation',
    'ticket_issue',
    'notification_send',
    'payment_capture',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
