export const cancellationRefundDelegationModuleManifest = {
  seed_id: "seed_6c_110_cancellation_refund_delegation",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.cancellation_refund_delegation",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Cancellation state with refund delegated to Finance/payment",
  proposed_model_name: "Phase6CCancellationRefundDelegation",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-014", "6C-EVENT-REG-003", "6C-ADL-003", "6C-BILL-007"],
  dependency_refs: [
    "seed_6a_service_manifest_contract",
    "6B.01",
    "6B.09",
    "6B.10",
    "6B.04",
    "6C.07",
    "seed_6c_001_employee_person_extension",
  ],
  adl_refs: ["ADL-001"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_type_ref",
    "cancellation_state",
    "cancellation_requested_at",
    "paid_registration",
    "refund_eligible",
    "refund_request_ref",
    "refund_ref",
    "finance_delegation_ref",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_configuration_and_registration_service.cancellation_refund_delegation.runtime_evaluated"],
  evidence_artifacts: [
    "cancellation_refund_delegation_runtime_receipt",
    "cancellation_refund_delegation_validation_result",
    "cancellation_refund_delegation_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "direct_refund_execution",
    "payment_mutation",
    "invoice_mutation",
    "ticket_reissue",
    "provider_sync",
    "persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
