export const eventCalendarScheduleRefModuleManifest = {
  seed_id: "seed_6c_105_event_calendar_schedule_ref",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.event_calendar_schedule_ref",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Event scheduling via Workspace Calendar refs",
  proposed_model_name: "Phase6CEventCalendarScheduleRef",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-009", "6C-EVENT-REG-012", "6C-EVENT-REG-003", "6C-BILL-007"],
  dependency_refs: [
    "seed_6a_service_manifest_contract",
    "6B.01",
    "6B.09",
    "6B.10",
    "6B.04",
    "6C.07",
    "seed_6c_001_employee_person_extension",
  ],
  conditional_dependencies: [
    { target: "6C.07", condition: "workspace_calendar_active" },
    { target: "6B.04", condition: "event_crm_handoff_active" },
  ],
  adl_refs: ["ADL-001"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "source_record_ref",
    "event_start_at",
    "event_end_at",
    "timezone",
    "calendar_schedule_ref",
    "calendar_owner_ref",
    "calendar_id_ref",
    "calendar_event_ref",
    "sync_status",
    "conflict_refs",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_configuration_and_registration_service.event_calendar_schedule_ref.runtime_evaluated"],
  evidence_artifacts: [
    "event_calendar_schedule_ref_runtime_receipt",
    "event_calendar_schedule_ref_validation_result",
    "event_calendar_schedule_ref_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "calendar_event_creation",
    "calendar_event_update",
    "workspace_calendar_provider_sync",
    "calendar_api_publication",
    "registration_invoice_mutation",
    "crm_handoff_mutation",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
