export const eventLeadHandoffModuleManifest = {
  seed_id: "seed_6c_107_event_lead_handoff",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.event_lead_handoff",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Event lead handoff events, not CRM direct writes",
  proposed_model_name: "Phase6CEventLeadHandoff",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-012"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
