export const eventLeadHandoffModuleManifest = {
  seed_id: "seed_6c_107_event_lead_handoff",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.event_lead_handoff",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Event lead handoff events, not CRM direct writes",
  proposed_model_name: "Phase6CEventLeadHandoff",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-012", "6C-GLOBAL-018", "6C-EVENT-REG-003", "6C-BILL-007"],
  dependency_refs: [
    "seed_6a_service_manifest_contract",
    "6B.01",
    "6B.09",
    "6B.10",
    "6B.04",
    "6C.07",
    "seed_6c_001_employee_person_extension",
  ],
  conditional_dependencies: [
    { target: "6B.04", condition: "event_crm_handoff_active" },
    { target: "6C.07", condition: "workspace_calendar_active" },
  ],
  adl_refs: ["ADL-001"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "source_record_ref",
    "crm_handoff_active",
    "handoff_status",
    "handoff_envelope",
    "conflict_refs",
    "runtime_evidence_digest",
  ],
  emitted_events: [
    "phase_6c.events_configuration_and_registration_service.event_lead_handoff.runtime_evaluated",
    "phase_6c.events_configuration_and_registration_service.event_lead_handoff.ready",
  ],
  evidence_artifacts: [
    "event_lead_handoff_runtime_receipt",
    "event_lead_handoff_validation_result",
    "event_lead_handoff_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "crm_direct_write",
    "crm_provider_sync",
    "event_bus_publication",
    "registration_mutation",
    "payment_mutation",
    "persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
