export const eventSessionTrackModuleManifest = {
  seed_id: 'seed_6c_097_event_session_track',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.event_session_track',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Multi-track session model',
  proposed_model_name: 'Phase6CEventSessionTrack',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-013', '6C-EVENT-REG-002', '6C-EVENT-REG-003', '6C-EVENT-REG-009', '6C-BILL-007', '6C-GLOBAL-018'],
  adl_refs: ['ADL-001'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'session_track_id',
    'track_code',
    'session_refs',
    'capacity_mode',
    'product_catalogue_ref',
    'ticket_type_ref',
    'registration_invoice_saga_ref',
    'calendar_schedule_ref',
    'event_session_track_runtime_digest',
  ],
  evidence_artifacts: [
    'event_session_track_runtime_receipt',
    'event_session_track_validation_result',
    'event_session_track_forbidden_behavior_rejection_evidence',
  ],
  external_dependency_contracts: [
    {
      target: '6B.01',
      basis: 'business_logic_hard_rule',
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-002', '6C-BILL-007'],
    },
    {
      target: '6B.09',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-001'],
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-003', '6C-ADL-003'],
    },
    {
      target: '6B.10',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-001'],
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-003', '6C-ADL-003'],
    },
    {
      target: '6C.07',
      basis: 'conditional_dependency',
      condition: 'workspace_calendar_active',
      refs_events_only: true,
      register_citation: ['6C-RECRUIT-005', '6C-EVENT-REG-009'],
    },
  ],
  forbidden_behaviors: [
    'product_catalogue_write',
    'finance_invoice_write',
    'payment_capture',
    'calendar_direct_write',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
