export const registrationInvoiceSagaModuleManifest = {
  seed_id: "seed_6c_108_registration_invoice_saga",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.registration_invoice_saga",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Registration invoice/payment/ticket Saga",
  proposed_model_name: "Phase6CRegistrationInvoiceSaga",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-003", "6C-ADL-003", "6C-HR-OPS-011", "6C-ADL-002", "6C-ADL-004", "6C-BILL-007"],
  dependency_refs: [
    "seed_6a_service_manifest_contract",
    "6B.01",
    "6B.09",
    "6B.10",
    "6A.08",
    "6B.04",
    "6C.07",
    "seed_6c_001_employee_person_extension",
  ],
  adl_refs: ["ADL-001", "ADL-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_type_ref",
    "paid_registration",
    "saga_stage",
    "saga_steps",
    "dependency_trace",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_configuration_and_registration_service.registration_invoice_saga.runtime_evaluated"],
  evidence_artifacts: [
    "registration_invoice_saga_runtime_receipt",
    "registration_invoice_saga_validation_result",
    "registration_invoice_saga_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "two_phase_commit",
    "direct_invoice_mutation",
    "direct_payment_capture",
    "direct_ticket_issue",
    "outbox_dispatch",
    "dlq_replay",
    "persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
