export const registrationAttemptEvidenceModuleManifest = {
  seed_id: "seed_6c_109_registration_attempt_evidence",
  component_id: "6C.08",
  component_slug: "events_configuration_and_registration_service",
  module_key: "phase-6c.events-configuration-and-registration-service",
  capability_surface: "phase_6c.events_configuration_and_registration_service.registration_attempt_evidence",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Evidence for every registration attempt",
  proposed_model_name: "Phase6CRegistrationAttemptEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-REG-018", "6C-EVENT-REG-002", "6C-EVENT-REG-003", "6C-EVENT-REG-012", "6C-EVENT-REG-009"],
  dependency_refs: [
    "seed_6a_service_manifest_contract",
    "6B.01",
    "6B.09",
    "6B.10",
    "6B.04",
    "6C.07",
    "seed_6c_001_employee_person_extension",
  ],
  adl_refs: ["ADL-001"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "attempt_ref",
    "event_config_ref",
    "attendee_ref",
    "ticket_type_ref",
    "source_record_ref",
    "attempted_at",
    "outcome",
    "registration_ref",
    "approval_ref",
    "payment_saga_ref",
    "waitlist_ref",
    "capacity_snapshot_ref",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_configuration_and_registration_service.registration_attempt_evidence.runtime_evaluated"],
  evidence_artifacts: [
    "registration_attempt_evidence_runtime_receipt",
    "registration_attempt_evidence_validation_result",
    "registration_attempt_evidence_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "registration_mutation",
    "payment_capture",
    "waitlist_mutation",
    "approval_mutation",
    "evidence_persistence",
    "event_publication",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
