export const registrationFormConfigModuleManifest = {
  seed_id: 'seed_6c_100_registration_form_config',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.registration_form_config',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Registration forms through Configuration Engine',
  proposed_model_name: 'Phase6CRegistrationFormConfig',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-004', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'registration_form_config_id',
    'configuration_engine_ref',
    'form_version',
    'field_configs',
    'sensitive_field_purpose_refs',
    'registration_form_config_runtime_digest',
  ],
  evidence_artifacts: [
    'registration_form_config_runtime_receipt',
    'registration_form_config_validation_result',
    'registration_form_config_forbidden_behavior_rejection_evidence',
  ],
  configuration_engine_required: true,
  forbidden_behaviors: [
    'frontend_render',
    'submission_processing',
    'configuration_write',
    'dynamic_code_execution',
    'file_upload',
    'provider_adapter_execution',
    'schema_mutation',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
