export const PHASE_6C_SPEAKER_HONORARIUM_REF_SEED_ID = 'seed_6c_098_speaker_honorarium_ref' as const;
export const PHASE_6C_SPEAKER_HONORARIUM_REF_COMPONENT_ID = '6C.08' as const;
export const SPEAKER_HONORARIUM_REF_RUNTIME_EVENT = 'phase_6c.events_configuration_and_registration_service.speaker_honorarium_ref.runtime_evaluated' as const;

export type SpeakerHonorariumLinkMode = 'PERSON_REF' | 'EXTERNAL_SPEAKER_REF';
export type SpeakerHonorariumDecision = 'SPEAKER_REF_READY' | 'HONORARIUM_REF_READY' | 'HONORARIUM_REQUIRES_APPROVAL_EVIDENCE';

export type SpeakerHonorariumTerms = {
  enabled: boolean;
  honorarium_ref?: string;
  amount_minor_units?: number;
  currency?: string;
  approval_evidence_ref?: string;
  finance_evidence_ref?: string;
  payment_evidence_ref?: string;
};

export type SpeakerHonorariumRefInput = {
  organization_id: string;
  service_manifest_contract_id: string;
  event_configuration_id: string;
  speaker_ref_record_id: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  speaker_display_name: string;
  person_ref?: string;
  external_speaker_ref?: string;
  session_refs: readonly string[];
  contract_ref?: string;
  honorarium_terms: SpeakerHonorariumTerms;
  control_metadata?: Record<string, unknown>;
  person_identity_write_requested?: boolean;
  finance_invoice_write_requested?: boolean;
  payment_capture_requested?: boolean;
  payroll_write_requested?: boolean;
  provider_adapter_requested?: boolean;
  persistence_requested?: boolean;
  schema_mutation_requested?: boolean;
  frontend_requested?: boolean;
};

export type SpeakerHonorariumRefRuntimeReceipt = {
  seed_id: typeof PHASE_6C_SPEAKER_HONORARIUM_REF_SEED_ID;
  component_id: typeof PHASE_6C_SPEAKER_HONORARIUM_REF_COMPONENT_ID;
  component_slug: 'events_configuration_and_registration_service';
  model_name: 'Phase6CSpeakerHonorariumRef';
  event_name: typeof SPEAKER_HONORARIUM_REF_RUNTIME_EVENT;
  organization_id: string;
  service_manifest_contract_id: string;
  event_configuration_id: string;
  speaker_ref_record_id: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  speaker_display_name: string;
  speaker_link_mode: SpeakerHonorariumLinkMode;
  person_ref?: string;
  external_speaker_ref?: string;
  session_count: number;
  session_refs: readonly string[];
  contract_ref?: string;
  honorarium_enabled: boolean;
  honorarium_ref?: string;
  amount_minor_units?: number;
  currency?: string;
  approval_evidence_ref?: string;
  finance_evidence_ref?: string;
  payment_evidence_ref?: string;
  decision: SpeakerHonorariumDecision;
  refs_events_only: true;
  direct_person_identity_write_allowed: false;
  direct_finance_write_allowed: false;
  direct_payment_capture_allowed: false;
  provider_adapter_allowed: false;
  persistence_performed: false;
  schema_mutation_performed: false;
  frontend_surface_created: false;
  decision_refs: readonly string[];
  evidence_artifacts: readonly string[];
  control_metadata: Record<string, unknown>;
  speaker_honorarium_ref_runtime_digest: string;
};
