export const speakerHonorariumRefModuleManifest = {
  seed_id: 'seed_6c_098_speaker_honorarium_ref',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.speaker_honorarium_ref',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Speaker and honorarium refs',
  proposed_model_name: 'Phase6CSpeakerHonorariumRef',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-010', '6C-EVENT-REG-003', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'speaker_ref_record_id',
    'speaker_display_name',
    'person_ref_or_external_speaker_ref',
    'session_refs',
    'contract_ref',
    'honorarium_ref',
    'finance_evidence_ref',
    'payment_evidence_ref',
    'speaker_honorarium_ref_runtime_digest',
  ],
  evidence_artifacts: [
    'speaker_honorarium_ref_runtime_receipt',
    'speaker_honorarium_ref_validation_result',
    'speaker_honorarium_ref_forbidden_behavior_rejection_evidence',
  ],
  external_dependency_contracts: [
    {
      target: '6B.09',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-001'],
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-003', '6C-ADL-003'],
    },
    {
      target: '6B.10',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-001'],
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-003', '6C-ADL-003'],
    },
  ],
  forbidden_behaviors: [
    'person_identity_write',
    'finance_invoice_write',
    'payment_capture',
    'payroll_write',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
