export const PHASE_6C_TICKET_CLAIM_DEADLINE_SEED_ID = 'seed_6c_103_ticket_claim_deadline' as const;
export const PHASE_6C_TICKET_CLAIM_DEADLINE_COMPONENT_ID = '6C.08' as const;
export const TICKET_CLAIM_DEADLINE_RUNTIME_EVENT = 'phase_6c.events_configuration_and_registration_service.ticket_claim_deadline.runtime_evaluated' as const;

export type TicketClaimDeadlineDecision = 'CLAIM_NOT_YET_OPEN' | 'CLAIM_OPEN' | 'CLAIM_CAPTURED' | 'CLAIM_EXPIRED' | 'CLAIM_REQUIRES_REVIEW';

export type TicketClaimDeadlineInput = {
  organization_id: string;
  service_manifest_contract_id: string;
  event_configuration_id: string;
  ticket_claim_ref: string;
  ticket_type_ref: string;
  registration_ref: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  issued_at: string;
  claim_opens_at?: string;
  claim_deadline_at: string;
  claimed_at?: string;
  grace_minutes?: number;
  control_metadata?: Record<string, unknown>;
  ticket_issue_mutation_requested?: boolean;
  ticket_claim_mutation_requested?: boolean;
  ticket_cancel_mutation_requested?: boolean;
  notification_send_requested?: boolean;
  scheduler_job_requested?: boolean;
  payment_capture_requested?: boolean;
  provider_adapter_requested?: boolean;
  persistence_requested?: boolean;
  schema_mutation_requested?: boolean;
  frontend_requested?: boolean;
};

export type TicketClaimDeadlineRuntimeReceipt = {
  seed_id: typeof PHASE_6C_TICKET_CLAIM_DEADLINE_SEED_ID;
  component_id: typeof PHASE_6C_TICKET_CLAIM_DEADLINE_COMPONENT_ID;
  component_slug: 'events_configuration_and_registration_service';
  model_name: 'Phase6CTicketClaimDeadline';
  event_name: typeof TICKET_CLAIM_DEADLINE_RUNTIME_EVENT;
  organization_id: string;
  service_manifest_contract_id: string;
  event_configuration_id: string;
  ticket_claim_ref: string;
  ticket_type_ref: string;
  registration_ref: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  issued_at: string;
  claim_opens_at: string;
  claim_deadline_at: string;
  effective_deadline_at: string;
  claimed_at?: string;
  grace_minutes: number;
  decision: TicketClaimDeadlineDecision;
  decision_reason: string;
  adl_refs: readonly string[];
  ticket_issue_mutation_performed: false;
  ticket_claim_mutation_performed: false;
  ticket_cancel_mutation_performed: false;
  notification_send_performed: false;
  scheduler_job_created: false;
  payment_capture_allowed: false;
  provider_adapter_allowed: false;
  persistence_performed: false;
  schema_mutation_performed: false;
  frontend_surface_created: false;
  decision_refs: readonly string[];
  evidence_artifacts: readonly string[];
  control_metadata: Record<string, unknown>;
  ticket_claim_deadline_runtime_digest: string;
};
