export const ticketClaimDeadlineModuleManifest = {
  seed_id: 'seed_6c_103_ticket_claim_deadline',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.ticket_claim_deadline',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Ticket claim deadlines',
  proposed_model_name: 'Phase6CTicketClaimDeadline',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-007', '6C-GLOBAL-018'],
  adl_refs: ['ADL-023'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'ticket_claim_ref',
    'ticket_type_ref',
    'registration_ref',
    'issued_at',
    'claim_opens_at',
    'claim_deadline_at',
    'effective_deadline_at',
    'claimed_at',
    'ticket_claim_deadline_runtime_digest',
  ],
  evidence_artifacts: [
    'ticket_claim_deadline_runtime_receipt',
    'ticket_claim_deadline_validation_result',
    'ticket_claim_deadline_forbidden_behavior_rejection_evidence',
  ],
  timed_dependency_contract: {
    basis: 'adl_hard_rule',
    adl_refs: ['ADL-023'],
    register_citation: ['6C-EVENT-REG-007'],
  },
  forbidden_behaviors: [
    'ticket_issue_mutation',
    'ticket_claim_mutation',
    'ticket_cancel_mutation',
    'notification_send',
    'scheduler_job_creation',
    'payment_capture',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
