export const ticketTypeCapacityModuleManifest = {
  seed_id: 'seed_6c_099_ticket_type_capacity',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.ticket_type_capacity',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Ticket-type capacity rules',
  proposed_model_name: 'Phase6CTicketTypeCapacity',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-016', '6C-EVENT-REG-002', '6C-BILL-007', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'product_catalogue_ref',
    'ticket_type_ref',
    'product_catalogue_item_ref',
    'capacity',
    'sold_count',
    'held_count',
    'reserved_count',
    'capacity_request',
    'ticket_type_capacity_runtime_digest',
  ],
  evidence_artifacts: [
    'ticket_type_capacity_runtime_receipt',
    'ticket_type_capacity_validation_result',
    'ticket_type_capacity_forbidden_behavior_rejection_evidence',
  ],
  external_dependency_contracts: [
    {
      target: '6B.01',
      basis: 'business_logic_hard_rule',
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-002', '6C-BILL-007'],
    },
  ],
  forbidden_behaviors: [
    'product_catalogue_write',
    'ticket_inventory_mutation',
    'payment_capture',
    'registration_creation',
    'waitlist_promotion',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
