export const waitlistRuleModuleManifest = {
  seed_id: 'seed_6c_101_waitlist_rule',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.waitlist_rule',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Configurable waitlist rules',
  proposed_model_name: 'Phase6CWaitlistRule',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-005', '6C-EVENT-REG-002', '6C-GLOBAL-018'],
  adl_refs: ['ADL-023'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'product_catalogue_ref',
    'ticket_type_ref',
    'waitlist_enabled',
    'max_waitlist_size',
    'join_policy',
    'ranking_strategy',
    'candidate_request',
    'waitlist_rule_runtime_digest',
  ],
  evidence_artifacts: [
    'waitlist_rule_runtime_receipt',
    'waitlist_rule_validation_result',
    'waitlist_rule_forbidden_behavior_rejection_evidence',
  ],
  external_dependency_contracts: [
    {
      target: '6B.01',
      basis: 'business_logic_hard_rule',
      refs_events_only: true,
      register_citation: ['6C-EVENT-REG-002', '6C-BILL-007'],
    },
  ],
  forbidden_behaviors: [
    'waitlist_entry_mutation',
    'ticket_inventory_mutation',
    'auto_promotion_execution',
    'payment_capture',
    'notification_send',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
