export const waitlistAutoPromotionTimerModuleManifest = {
  seed_id: 'seed_6c_102_waitlist_auto_promotion_timer',
  component_id: '6C.08',
  component_slug: 'events_configuration_and_registration_service',
  module_key: 'phase-6c.events-configuration-and-registration-service',
  capability_surface: 'phase_6c.events_configuration_and_registration_service.waitlist_auto_promotion_timer',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Waitlist auto-promotion timer',
  proposed_model_name: 'Phase6CWaitlistAutoPromotionTimer',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-EVENT-REG-006', '6C-ADL-006', '6C-GLOBAL-018'],
  adl_refs: ['ADL-023'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_configuration_id',
    'timer_ref',
    'waitlist_entry_ref',
    'ticket_type_ref',
    'eligible_at',
    'expires_at',
    'capacity_available',
    'priority_rank',
    'waitlist_auto_promotion_timer_runtime_digest',
  ],
  evidence_artifacts: [
    'waitlist_auto_promotion_timer_runtime_receipt',
    'waitlist_auto_promotion_timer_validation_result',
    'waitlist_auto_promotion_timer_forbidden_behavior_rejection_evidence',
  ],
  timed_dependency_contract: {
    basis: 'adl_hard_rule',
    adl_refs: ['ADL-023'],
    register_citation: ['6C-EVENT-REG-006', '6C-ADL-006'],
  },
  forbidden_behaviors: [
    'scheduler_job_creation',
    'waitlist_promotion_mutation',
    'ticket_inventory_mutation',
    'notification_send',
    'payment_capture',
    'provider_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
