export const apiLeadIntakeModuleManifest = {
  seed_id: 'seed_6b_04_api_lead_intake',
  component_id: '6B.04',
  capability_surface: 'crm_lead_intake.api_lead_intake',
  source_system: 'API_LEAD_INTAKE',
  activation_lifecycle_required: true,
  person_identity_graph_required: true,
  access_core_gatekeeper_required: true,
  api_key_scope_registry_required: true,
  visual_workflow_builder_required: true,
  product_record_authority_required: true,
  conditional_dependencies: {
    global_opt_out_registry: 'observed_at_intake_not_hard_send_gate',
  },
  owned_data: [
    'api_request_id',
    'api_endpoint_id',
    'api_client_id',
    'api_key_scope_registry_id',
    'external_source_reference',
    'payload_fields',
    'source_metadata',
    'intake_mapping',
    'lead_record_authority_reference',
  ],
  forbidden_behaviors: [
    'direct_provider_messaging',
    'provider_callback_processing',
    'credential_material_storage',
    'communication_send',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
