export const chatbotIntakeModuleManifest = {
  seed_id: 'seed_6b_04_chatbot_intake',
  component_id: '6B.04',
  capability_surface: 'crm_lead_intake.chatbot_intake',
  source_system: 'CHATBOT_INTAKE',
  activation_lifecycle_required: true,
  person_identity_graph_required: true,
  access_core_gatekeeper_required: true,
  visual_workflow_builder_required: true,
  product_record_authority_required: true,
  conditional_dependencies: {
    global_opt_out_registry: 'observed_at_intake_not_hard_send_gate',
  },
  owned_data: [
    'chatbot_surface_id',
    'chatbot_session_id',
    'chatbot_conversation_ref',
    'chatbot_flow_id',
    'channel',
    'handoff_state',
    'lead_fields',
    'conversation_evidence',
    'intake_mapping',
    'lead_record_authority_reference',
  ],
  forbidden_behaviors: [
    'runtime_ai_decisioning',
    'outbound_send',
    'direct_provider_messaging',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
