export const emailIntakeModuleManifest = {
  seed_id: 'seed_6b_04_email_intake',
  component_id: '6B.04',
  capability_surface: 'crm_lead_intake.email_intake',
  source_system: 'EMAIL_INTAKE',
  activation_lifecycle_required: true,
  person_identity_graph_required: true,
  access_core_gatekeeper_required: true,
  visual_workflow_builder_required: true,
  product_record_authority_required: true,
  conditional_dependencies: {
    global_opt_out_registry: 'observed_at_intake_not_hard_send_gate',
  },
  owned_data: [
    'inbound_mailbox_id',
    'email_message_ref',
    'email_thread_ref',
    'sender_email_ref',
    'subject_ref',
    'message_type',
    'lead_fields',
    'email_evidence',
    'intake_mapping',
    'lead_record_authority_reference',
  ],
  forbidden_behaviors: [
    'outbound_send',
    'direct_provider_messaging',
    'provider_callback_processing',
    'credential_material_storage',
    'deliverability_management',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
