export const phoneIntakeModuleManifest = {
  seed_id: 'seed_6b_04_phone_intake',
  component_id: '6B.04',
  capability_surface: 'crm_lead_intake.phone_intake',
  source_system: 'PHONE_INTAKE',
  activation_lifecycle_required: true,
  person_identity_graph_required: true,
  access_core_gatekeeper_required: true,
  visual_workflow_builder_required: true,
  product_record_authority_required: true,
  conditional_dependencies: {
    global_opt_out_registry: 'observed_at_intake_not_hard_send_gate',
  },
  owned_data: [
    'phone_channel_id',
    'caller_phone_ref',
    'call_reference_id',
    'operator_user_id',
    'call_direction',
    'call_outcome',
    'lead_fields',
    'call_evidence',
    'intake_mapping',
    'lead_record_authority_reference',
  ],
  forbidden_behaviors: [
    'outbound_call',
    'direct_provider_messaging',
    'provider_callback_processing',
    'credential_material_storage',
    'production_telephony_adapter',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
