export const walkInIntakeModuleManifest = {
  seed_id: 'seed_6b_04_walk_in_intake',
  component_id: '6B.04',
  capability_surface: 'crm_lead_intake.walk_in_intake',
  source_system: 'WALK_IN_INTAKE',
  activation_lifecycle_required: true,
  person_identity_graph_required: true,
  access_core_gatekeeper_required: true,
  visual_workflow_builder_required: true,
  product_record_authority_required: true,
  conditional_dependencies: {
    global_opt_out_registry: 'observed_at_intake_not_hard_send_gate',
  },
  owned_data: [
    'walk_in_location_ref',
    'visit_reference_id',
    'captured_by_user_id',
    'visit_type',
    'visit_outcome',
    'lead_fields',
    'visit_evidence',
    'intake_mapping',
    'lead_record_authority_reference',
  ],
  forbidden_behaviors: [
    'outbound_send',
    'direct_provider_messaging',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
