export const attendanceLocationRedactionModuleManifest = {
  seed_id: "seed_6c_039_attendance_location_redaction",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.attendance_location_redaction",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Sensitive attendance location redaction",
  proposed_model_name: "Phase6CAttendanceLocationRedaction",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-020"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "attendance_event_ref",
    "employee_ref",
    "requester_purpose",
    "redaction_profile",
    "redacted_latitude",
    "redacted_longitude",
    "region_code",
    "provider_location_ref_hash",
    "raw_location_hash",
    "attendance_location_redaction_evidence_digest",
  ],
  required_evidence_artifacts: [
    "attendance_location_redaction_receipt",
    "attendance_location_privacy_evidence",
    "provider_location_hash_evidence",
  ],
  forbidden_behaviors: [
    "unauthorized_raw_location_disclosure",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
