export const attendanceExceptionDetectionModuleManifest = {
  seed_id: "seed_6c_030_attendance_exception_detection",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.attendance_exception_detection",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Duplicate, clock-skew, late, and missing-checkout exceptions",
  proposed_model_name: "Phase6CAttendanceExceptionDetection",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-001", "6C-ATT-002", "6C-ATT-007", "6C-ATT-008", "6C-ATT-019"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "attendance_date",
    "scheduled_start_at",
    "scheduled_end_at",
    "server_recorded_at",
    "actual_check_in_at",
    "actual_check_out_at",
    "device_captured_at",
    "max_clock_skew_seconds",
    "late_grace_period_minutes",
    "missing_checkout_grace_period_minutes",
    "observed_clock_skew_seconds",
    "observed_late_minutes",
    "missing_checkout_elapsed_minutes",
    "duplicate_detected",
    "exception_detection_evidence_digest",
  ],
  required_evidence_artifacts: [
    "attendance_exception_detection_decision_receipt",
    "attendance_exception_detection_threshold_evidence",
    "attendance_exception_detection_exception_records",
  ],
  forbidden_behaviors: [
    "direct_attendance_record_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
