export const PHASE_6C_BIOMETRIC_DEVICE_BOUNDARY_SEED_ID = 'seed_6c_025_biometric_device_boundary' as const;
export const PHASE_6C_BIOMETRIC_DEVICE_BOUNDARY_COMPONENT_ID = '6C.03' as const;
export const BIOMETRIC_DEVICE_BOUNDARY_RUNTIME_EVENT = 'phase_6c.hr_attendance_leave_and_time_tracking.biometric_device_boundary.evaluated' as const;

export type BiometricDeviceFamily = 'FINGERPRINT' | 'FACE' | 'PALM' | 'VOICE';
export type BiometricBoundaryDecision = 'BOUNDARY_ACCEPTED' | 'BOUNDARY_REJECTED';

export type BiometricDeviceBoundaryInput = {
  organization_id: string;
  service_manifest_contract_id: string;
  source_record_ref: string;
  employee_ref: string;
  device_boundary_ref: string;
  provider_neutral_device_ref: string;
  device_family: BiometricDeviceFamily;
  biometric_evidence_ref: string;
  captured_at: string;
  received_at: string;
  fallback_method_ref?: string;
  evaluated_by_user_id: string;
  control_metadata?: Record<string, unknown>;
  real_brand_adapter_requested?: boolean;
  provider_credentials_requested?: boolean;
  raw_biometric_capture_requested?: boolean;
  biometric_template_storage_requested?: boolean;
  external_device_call_requested?: boolean;
  attendance_record_mutation_requested?: boolean;
  schema_mutation_requested?: boolean;
  phase_6a_mutation_requested?: boolean;
  phase_6b_mutation_requested?: boolean;
  runtime_adapter_requested?: boolean;
  ticket_flag_flip_requested?: boolean;
};

export type BiometricDeviceBoundaryReceipt = {
  seed_id: typeof PHASE_6C_BIOMETRIC_DEVICE_BOUNDARY_SEED_ID;
  component_id: typeof PHASE_6C_BIOMETRIC_DEVICE_BOUNDARY_COMPONENT_ID;
  component_slug: 'hr_attendance_leave_and_time_tracking';
  model_name: 'Phase6CBiometricDeviceBoundary';
  event_name: typeof BIOMETRIC_DEVICE_BOUNDARY_RUNTIME_EVENT;
  organization_id: string;
  service_manifest_contract_id: string;
  source_record_ref: string;
  employee_ref: string;
  runtime_status: 'BIOMETRIC_DEVICE_BOUNDARY_EVALUATED';
  decision: BiometricBoundaryDecision;
  rejection_reasons: readonly string[];
  provider_neutral_only: true;
  real_brand_adapter_allowed: false;
  provider_credentials_allowed: false;
  raw_biometric_capture_allowed: false;
  biometric_template_storage_allowed: false;
  external_device_call_allowed: false;
  fallback_methods_allowed: true;
  device_boundary_ref: string;
  provider_neutral_device_ref: string;
  device_family: BiometricDeviceFamily;
  biometric_evidence_ref: string;
  fallback_method_ref: string | null;
  decision_refs: readonly string[];
  evidence_artifacts: readonly string[];
  control_metadata: Record<string, unknown>;
  evaluated_by_user_id: string;
  received_at: string;
  biometric_device_boundary_evidence_digest: string;
};
