export const biometricDeviceBoundaryModuleManifest = {
  seed_id: 'seed_6c_025_biometric_device_boundary',
  component_id: '6C.03',
  component_slug: 'hr_attendance_leave_and_time_tracking',
  module_key: 'phase-6c.hr-attendance-leave-and-time-tracking',
  capability_surface: 'phase_6c.hr_attendance_leave_and_time_tracking.biometric_device_boundary',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Provider-neutral biometric device boundary',
  proposed_model_name: 'Phase6CBiometricDeviceBoundary',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  provider_neutral_only: true,
  real_brand_adapter_allowed: false,
  provider_credentials_allowed: false,
  raw_biometric_capture_allowed: false,
  biometric_template_storage_allowed: false,
  external_device_call_allowed: false,
  fallback_methods_allowed: true,
  location_sensitive_redacted: true,
  decision_refs: ['6C-ATT-001', '6C-ATT-002', '6C-ATT-003', '6C-ATT-019', '6C-ATT-020'],
  conditional_dependency_refs: ['attendance_provider_or_channel_active'],
  evidence_artifacts: [
    'biometric_device_boundary_runtime_receipt',
    'biometric_device_boundary_validation_result',
    'biometric_device_boundary_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'employee_ref',
    'device_boundary_ref',
    'provider_neutral_device_ref',
    'device_family',
    'biometric_evidence_ref',
    'fallback_method_ref',
    'rejection_reasons',
    'control_metadata',
    'biometric_device_boundary_evidence_digest',
  ],
  forbidden_behaviors: [
    'real_brand_adapter_execution',
    'provider_credentials_handling',
    'raw_biometric_capture',
    'biometric_template_storage',
    'external_device_call',
    'attendance_record_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
