export const leaveAccrualEngineModuleManifest = {
  seed_id: "seed_6c_034_leave_accrual_engine",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.leave_accrual_engine",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Leave accrual rule engine",
  proposed_model_name: "Phase6CLeaveAccrualEngine",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-002", "6C-ATT-014", "6C-ATT-015", "6C-ATT-019"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "leave_type_ref",
    "accrual_rule_ref",
    "accrual_frequency",
    "annual_entitlement_units",
    "raw_accrual_units",
    "rounded_accrual_units",
    "cap_adjustment_units",
    "projected_balance_units",
    "leave_accrual_evidence_digest",
  ],
  required_evidence_artifacts: [
    "leave_accrual_decision_receipt",
    "leave_accrual_formula_evidence",
    "leave_accrual_cap_evidence",
  ],
  forbidden_behaviors: [
    "direct_balance_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
