export const leaveTypeRegistryModuleManifest = {
  seed_id: "seed_6c_033_leave_type_registry",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.leave_type_registry",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Configurable leave types",
  proposed_model_name: "Phase6CLeaveTypeRegistry",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-014"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
