export const manualAttendanceOverrideModuleManifest = {
  seed_id: "seed_6c_028_manual_attendance_override",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.manual_attendance_override",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Manual attendance override with reason and approval defaults",
  proposed_model_name: "Phase6CManualAttendanceOverride",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-001", "6C-ATT-002", "6C-ATT-008", "6C-ATT-010", "6C-ATT-011", "6C-ATT-019"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "override_action",
    "override_effective_at",
    "server_recorded_at",
    "reason_ref",
    "reason_text",
    "approval_required",
    "approval_ref",
    "duplicate_detected",
    "duplicate_exception_ref",
    "fallback_method_ref",
    "control_metadata",
    "override_evidence_digest",
  ],
  required_evidence_artifacts: [
    "manual_attendance_override_decision_receipt",
    "manual_attendance_override_reason_evidence",
    "manual_attendance_override_approval_default_evidence",
  ],
  forbidden_behaviors: [
    "reasonless_override",
    "approval_bypass",
    "direct_attendance_record_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
