export const mobileGpsAttendanceModuleManifest = {
  seed_id: 'seed_6c_027_mobile_gps_attendance',
  component_id: '6C.03',
  component_slug: 'hr_attendance_leave_and_time_tracking',
  module_key: 'phase-6c.hr-attendance-leave-and-time-tracking',
  capability_surface: 'phase_6c.hr_attendance_leave_and_time_tracking.mobile_gps_attendance',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Mobile GPS attendance with configurable liveness photo',
  proposed_model_name: 'Phase6CMobileGpsAttendance',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  provider_neutral_only: true,
  liveness_photo_configurable: true,
  offline_queue_supported: true,
  server_authoritative_record: true,
  location_sensitive_redacted: true,
  fallback_methods_allowed: true,
  raw_location_storage_allowed: false,
  attendance_record_mutation_allowed: false,
  decision_refs: ['6C-ATT-001', '6C-ATT-002', '6C-ATT-005', '6C-ATT-006', '6C-ATT-007', '6C-ATT-019', '6C-ATT-020'],
  conditional_dependency_refs: ['attendance_provider_or_channel_active'],
  evidence_artifacts: [
    'mobile_gps_attendance_runtime_receipt',
    'mobile_gps_attendance_validation_result',
    'mobile_gps_attendance_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'employee_ref',
    'mobile_device_ref',
    'location_policy_ref',
    'redacted_location_result',
    'clock_skew_seconds',
    'offline_queue_ref',
    'fallback_method_ref',
    'decision',
    'rejection_reasons',
    'control_metadata',
    'mobile_gps_attendance_evidence_digest',
  ],
  forbidden_behaviors: [
    'raw_location_storage',
    'provider_specific_adapter_execution',
    'attendance_record_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
