export const offlineAttendanceQueueModuleManifest = {
  seed_id: "seed_6c_029_offline_attendance_queue",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.offline_attendance_queue",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Offline attendance queue and replay evidence",
  proposed_model_name: "Phase6COfflineAttendanceQueue",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-001", "6C-ATT-002", "6C-ATT-006", "6C-ATT-007", "6C-ATT-008", "6C-ATT-019"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "offline_capture_ref",
    "attendance_method",
    "attendance_event_type",
    "captured_at_device",
    "queued_at",
    "server_received_at",
    "replay_requested_at",
    "connectivity_restored",
    "max_clock_skew_seconds",
    "observed_clock_skew_seconds",
    "duplicate_detected",
    "duplicate_exception_ref",
    "fallback_method_ref",
    "provider_channel_ref",
    "control_metadata",
    "offline_queue_evidence_digest",
  ],
  required_evidence_artifacts: [
    "offline_attendance_queue_decision_receipt",
    "offline_attendance_replay_evidence",
    "offline_attendance_clock_skew_evidence",
  ],
  forbidden_behaviors: [
    "direct_attendance_record_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
