export const payrollInputEvidenceModuleManifest = {
  seed_id: "seed_6c_038_payroll_input_evidence",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.payroll_input_evidence",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Attendance/leave payroll input evidence",
  proposed_model_name: "Phase6CPayrollInputEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-017"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "payroll_period_ref",
    "evidence_line_count",
    "attendance_hours",
    "overtime_hours",
    "paid_leave_units",
    "unpaid_leave_units",
    "absence_deduction_units",
    "leave_encashment_amount",
    "payroll_input_evidence_digest",
  ],
  required_evidence_artifacts: [
    "payroll_input_evidence_receipt",
    "attendance_payroll_summary_evidence",
    "leave_payroll_boundary_evidence",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "direct_balance_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
