export const qrAttendanceModuleManifest = {
  seed_id: 'seed_6c_024_qr_attendance',
  component_id: '6C.03',
  component_slug: 'hr_attendance_leave_and_time_tracking',
  module_key: 'phase-6c.hr-attendance-leave-and-time-tracking',
  capability_surface: 'phase_6c.hr_attendance_leave_and_time_tracking.qr_attendance',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Geofenced time-windowed QR attendance',
  proposed_model_name: 'Phase6CQrAttendance',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  provider_neutral_only: true,
  self_and_supervisor_scan_supported: true,
  liveness_photo_configurable: true,
  server_authoritative_record: true,
  time_window_adl_ref: 'ADL-024',
  location_sensitive_redacted: true,
  fallback_methods_allowed: true,
  attendance_record_mutation_allowed: false,
  decision_refs: ['6C-ATT-004', '6C-ATT-005', '6C-ATT-007', '6C-ATT-018', '6C-ATT-019', '6C-ATT-020', '6C-ADL-007'],
  adl_refs: ['ADL-024'],
  conditional_dependency_refs: ['attendance_provider_or_channel_active'],
  evidence_artifacts: [
    'qr_attendance_runtime_receipt',
    'qr_attendance_validation_result',
    'qr_attendance_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'employee_ref',
    'qr_token_ref',
    'scan_mode',
    'time_window_ref',
    'geofence_ref',
    'redacted_location_result',
    'clock_skew_seconds',
    'decision',
    'rejection_reasons',
    'control_metadata',
    'qr_attendance_evidence_digest',
  ],
  forbidden_behaviors: [
    'provider_specific_adapter_execution',
    'biometric_capture',
    'raw_location_storage',
    'attendance_record_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
