export const rfidNfcAttendanceModuleManifest = {
  seed_id: 'seed_6c_026_rfid_nfc_attendance',
  component_id: '6C.03',
  component_slug: 'hr_attendance_leave_and_time_tracking',
  module_key: 'phase-6c.hr-attendance-leave-and-time-tracking',
  capability_surface: 'phase_6c.hr_attendance_leave_and_time_tracking.rfid_nfc_attendance',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'RFID/NFC attendance method family',
  proposed_model_name: 'Phase6CRfidNfcAttendance',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  provider_neutral_only: true,
  offline_queue_supported: true,
  server_authoritative_record: true,
  fallback_methods_allowed: true,
  raw_tag_storage_allowed: false,
  external_reader_call_allowed: false,
  attendance_record_mutation_allowed: false,
  decision_refs: ['6C-ATT-001', '6C-ATT-002', '6C-ATT-006', '6C-ATT-007', '6C-ATT-019'],
  conditional_dependency_refs: ['attendance_provider_or_channel_active'],
  evidence_artifacts: [
    'rfid_nfc_attendance_runtime_receipt',
    'rfid_nfc_attendance_validation_result',
    'rfid_nfc_attendance_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'employee_ref',
    'method',
    'provider_neutral_reader_ref',
    'token_evidence_ref',
    'clock_skew_seconds',
    'offline_queue_ref',
    'fallback_method_ref',
    'decision',
    'rejection_reasons',
    'control_metadata',
    'rfid_nfc_attendance_evidence_digest',
  ],
  forbidden_behaviors: [
    'provider_specific_adapter_execution',
    'raw_tag_storage',
    'external_reader_call',
    'attendance_record_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
