export const shiftRosterModuleManifest = {
  seed_id: "seed_6c_031_shift_roster",
  component_id: "6C.03",
  component_slug: "hr_attendance_leave_and_time_tracking",
  module_key: "phase-6c.hr-attendance-leave-and-time-tracking",
  capability_surface: "phase_6c.hr_attendance_leave_and_time_tracking.shift_roster",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Shift and roster model",
  proposed_model_name: "Phase6CShiftRoster",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-ATT-002", "6C-ATT-012", "6C-ATT-019"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "roster_ref",
    "roster_pattern",
    "effective_from",
    "effective_to",
    "roster_timezone",
    "overlap_policy",
    "maximum_shift_minutes",
    "minimum_break_minutes",
    "assignments",
    "issues",
    "roster_evidence_digest",
  ],
  required_evidence_artifacts: [
    "shift_roster_decision_receipt",
    "shift_roster_assignment_evidence",
    "shift_roster_conflict_evidence",
  ],
  forbidden_behaviors: [
    "direct_attendance_record_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
