import { ModuleManifestSchema, type ModuleManifest } from "../module-manifest.schema.js";

export const phase6bModuleManifest: ModuleManifest = ModuleManifestSchema.parse({
  module_key: "phase-6b.banking-reconciliation",
  display_name: "Banking Reconciliation",
  display_metadata: {
    display_name: "Banking Reconciliation",
    display_description: "Phase 6B Banking Reconciliation scaffold-control manifest. This definition is metadata-only and does not authorize capability implementation.",
    display_features: ["Scaffold-control boundary", "No capability implementation authorized"],
    icon_key: "settings",
    category: "business",
    visibility_state: "locked",
    route: null,
  },
  ai_data_classification: "restricted",
  module_type: "standard",
  version: "0.1.0",
  owner: "phase-6b-scaffold-control",
  min_platform_version: "0.1.0",
  dependencies: [],
  optional_dependencies: [],
  capabilities: [],
  capabilities_consumed: [],
  required_capabilities: [],
  permissions: [],
  api_routes: [],
  events_emitted: [],
  events_consumed: [],
  schemas: [],
  migrations: [],
  settings: [],
  menu_entries: [],
  dashboard_widgets: [],
  gatekeeper_hooks: [],
  audit_hooks: [],
  health_checks: [],
  degraded_mode_behavior: {
    mode: "disabled",
    description: "Phase 6B Banking Reconciliation remains disabled until a later approved capability implementation ticket authorizes runtime behavior.",
    disabled_capabilities: [],
  },
  disable_behavior: {
    description: "Disabling this scaffold has no runtime behavior because capability implementation is not authorized.",
    blocks_dependent_modules: false,
    data_retention_required: false,
  },
  data_ownership: {
    owner_module_key: "phase-6b.banking-reconciliation",
    tenant_scoped: true,
    entity_refs: [],
    retention_policy: "No Phase 6B runtime entities are created by scaffold-control manifests.",
    sensitive_data: false,
  },
});
