export const agingAndOverdueManagementModuleManifest = {
  seed_id: 'seed_6b_09_aging_and_overdue_management',
  component_id: '6B.09',
  capability_surface: 'finance_invoice_receivables.aging_and_overdue_management',
  source_system: 'FINANCE_INVOICE_RECEIVABLES',
  activation_lifecycle_required: true,
  tenant_service: true,
  invoice_record_authority_required: true,
  receivable_balance_required: true,
  product_record_authority_required: true,
  product_price_history_required: true,
  pricing_table_effective_dates_required: true,
  pipeline_stage_model_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'receivable_id',
    'invoice_record_ref',
    'customer_account_ref',
    'payment_terms_ref',
    'receivable_balance_minor',
    'due_at',
    'days_past_due',
    'status',
    'aging_bucket_id',
    'aging_bucket_label',
    'disposition',
  ],
  forbidden_behaviors: [
    'payment_allocation_math',
    'communication_sending',
    'provider_callback_processing',
    'payment_capture',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
