export const fbrInvoiceFormatModuleManifest = {
  seed_id: 'seed_6b_09_fbr_invoice_format',
  component_id: '6B.09',
  capability_surface: 'finance_invoice_receivables.fbr_invoice_format',
  source_system: 'FINANCE_INVOICE_RECEIVABLES',
  activation_lifecycle_required: true,
  tenant_service: true,
  format_profile_configurable: true,
  invoice_record_authority_required: true,
  product_record_authority_required: true,
  product_price_history_required: true,
  pricing_table_effective_dates_required: true,
  pipeline_stage_model_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'format_profile_id',
    'fbr_format_version',
    'invoice_record_ref',
    'field_mappings',
    'invoice_values',
    'payload_fields',
    'format_evidence_digest',
  ],
  forbidden_behaviors: [
    'fbr_api_submission',
    'credential_material_storage',
    'tax_law_validation_claim',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
