export const invoiceRecordAuthorityModuleManifest = {
  seed_id: 'seed_6b_09_invoice_record_authority',
  component_id: '6B.09',
  capability_surface: 'finance_invoice_receivables.invoice_record_authority',
  source_system: 'FINANCE_INVOICE_RECEIVABLES',
  activation_lifecycle_required: true,
  tenant_service: true,
  invoice_immutable_after_issue: true,
  product_record_authority_required: true,
  product_price_history_required: true,
  pricing_table_effective_dates_required: true,
  pipeline_stage_model_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'invoice_id',
    'invoice_number',
    'customer_record_ref',
    'payment_terms',
    'status',
    'currency_code',
    'issued_at',
    'invoice_lines',
    'invoice_total_minor',
    'invoice_record_digest',
  ],
  forbidden_behaviors: [
    'payment_allocation_math',
    'invoice_send_execution',
    'issued_invoice_mutation',
    'credit_note_creation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
