export const invoiceLifecycleTypesModuleManifest = {
  seed_id: 'seed_6b_09_invoice_lifecycle_types',
  component_id: '6B.09',
  capability_surface: 'finance_invoice_receivables.invoice_lifecycle_types',
  source_system: 'FINANCE_INVOICE_RECEIVABLES',
  activation_lifecycle_required: true,
  tenant_service: true,
  invoice_immutable_after_issue: true,
  product_record_authority_required: true,
  product_price_history_required: true,
  pricing_table_effective_dates_required: true,
  pipeline_stage_model_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'invoice_id',
    'invoice_record_authority_ref',
    'current_status',
    'requested_status',
    'transition_kind',
    'transition_reason',
    'issued_at',
    'post_issue_change_policy',
  ],
  forbidden_behaviors: [
    'issued_invoice_mutation',
    'credit_note_creation',
    'payment_allocation_math',
    'invoice_send_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
