export const emailTransactionalDomainModuleManifest = {
  seed_id: 'seed_6b_07_email_transactional_domain',
  component_id: '6B.07',
  capability_surface: 'crm_communication.email_transactional_domain',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'transactional_domain_id',
    'domain_name',
    'default_from_address',
    'display_name',
    'pipeline_stage_model_ref',
    'global_opt_out_registry_ref',
    'outbound_gateway_enforcement_ref',
    'lifecycle_status',
    'verification_status',
    'dns_evidence',
  ],
  forbidden_behaviors: [
    'outbound_email_send',
    'provider_credential_storage',
    'dns_record_mutation',
    'provider_callback_processing',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
