export const emailSequencesModuleManifest = {
  seed_id: 'seed_6b_07_email_sequences',
  component_id: '6B.07',
  capability_surface: 'crm_communication.email_sequences',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'email_sequence_id',
    'sequence_name',
    'pipeline_stage_model_ref',
    'global_opt_out_registry_ref',
    'outbound_gateway_enforcement_ref',
    'enrollment_policy',
    'lifecycle_status',
    'steps',
  ],
  forbidden_behaviors: [
    'immediate_email_send',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
