export const emailSharedInboxModuleManifest = {
  seed_id: 'seed_6b_07_email_shared_inbox',
  component_id: '6B.07',
  capability_surface: 'crm_communication.email_shared_inbox',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'shared_inbox_id',
    'inbox_address',
    'display_name',
    'pipeline_stage_model_ref',
    'global_opt_out_registry_ref',
    'outbound_gateway_enforcement_ref',
    'thread_policy',
    'visibility',
    'owner_group_refs',
    'routing_queue_ref',
    'lifecycle_status',
  ],
  forbidden_behaviors: [
    'outbound_email_send',
    'mailbox_sync_execution',
    'credential_material_storage',
    'provider_callback_processing',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
