export const whatsappBroadcastComplianceModuleManifest = {
  seed_id: 'seed_6b_07_whatsapp_broadcast_compliance',
  component_id: '6B.07',
  capability_surface: 'crm_communication.whatsapp_broadcast_compliance',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'broadcast_compliance_check_id',
    'whatsapp_template_ref',
    'recipient_ref',
    'lead_record_authority_id',
    'conversation_ref',
    'opt_out_state',
    'outbound_window_state',
    'recipient_status',
    'compliance_evidence_refs',
  ],
  forbidden_behaviors: [
    'broadcast_send',
    'provider_send',
    'credential_material_storage',
    'global_opt_out_enforcement_bypass',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
