export const whatsappOutboundWindowModuleManifest = {
  seed_id: 'seed_6b_07_whatsapp_outbound_window',
  component_id: '6B.07',
  capability_surface: 'crm_communication.whatsapp_outbound_window',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'outbound_window_check_id',
    'lead_record_authority_id',
    'conversation_ref',
    'whatsapp_template_ref',
    'last_inbound_at',
    'candidate_send_at',
    'configured_window_minutes',
    'window_status',
  ],
  forbidden_behaviors: [
    'outbound_message_send',
    'provider_send',
    'credential_material_storage',
    'global_opt_out_enforcement_bypass',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
