export const whatsappTemplateManagementModuleManifest = {
  seed_id: 'seed_6b_07_whatsapp_template_management',
  component_id: '6B.07',
  capability_surface: 'crm_communication.whatsapp_template_management',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_tier: 'conditional_setup_reference',
  owned_data: [
    'whatsapp_template_id',
    'pipeline_stage_model_ref',
    'template_key',
    'category',
    'lifecycle_status',
    'language_code',
    'body_template',
    'variables',
    'approval_evidence_refs',
  ],
  forbidden_behaviors: [
    'outbound_message_send',
    'provider_template_submission',
    'credential_material_storage',
    'global_opt_out_enforcement_bypass',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
