export const whatsappInboundRoutingModuleManifest = {
  seed_id: 'seed_6b_07_whatsapp_inbound_routing',
  component_id: '6B.07',
  capability_surface: 'crm_communication.whatsapp_inbound_routing',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_tier: 'conditional_capture_reference',
  owned_data: [
    'inbound_message_id',
    'channel_account_ref',
    'sender_contact_ref',
    'conversation_ref',
    'lead_record_authority_id',
    'pipeline_stage_key',
    'message_kind',
    'routing_decision',
    'route_reason',
    'evidence_refs',
  ],
  forbidden_behaviors: [
    'outbound_message_send',
    'provider_callback_processing',
    'credential_material_storage',
    'global_opt_out_enforcement_bypass',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
