export const whatsappAutoReplyKeywordsModuleManifest = {
  seed_id: 'seed_6b_07_whatsapp_auto_reply_keywords',
  component_id: '6B.07',
  capability_surface: 'crm_communication.whatsapp_auto_reply_keywords',
  source_system: 'CRM_COMMUNICATION',
  activation_lifecycle_required: true,
  optional_microservice: true,
  pipeline_stage_model_required: true,
  global_opt_out_registry_required: true,
  outbound_gateway_enforcement_required: true,
  adl_refs: ['ADL-004'],
  owned_data: [
    'auto_reply_evaluation_id',
    'inbound_message_id',
    'conversation_ref',
    'lead_record_authority_id',
    'keyword_rule_id',
    'keyword',
    'match_type',
    'response_template_ref',
    'candidate_status',
  ],
  forbidden_behaviors: [
    'outbound_message_send',
    'provider_send',
    'credential_material_storage',
    'global_opt_out_enforcement_bypass',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
