export const attendanceCertificateEvidenceModuleManifest = {
  seed_id: "seed_6c_124_attendance_certificate_evidence",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.attendance_certificate_evidence",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Attendance certificate evidence only, LMS certification deferred",
  proposed_model_name: "Phase6CAttendanceCertificateEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-014", "6C-EVENT-REG-012", "6C-GLOBAL-018", "6C-NON-001"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_ref",
    "attendee_ref",
    "registration_ref",
    "source_record_ref",
    "certificate_scope",
    "identity_policy",
    "certificate_policy_ref",
    "attendance_summary",
    "checkin_evidence_refs",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.attendance_certificate_evidence.runtime_evaluated"],
  deferred_targets: ["6D.lms_certification_output"],
  forbidden_behaviors: [
    "lms_certification_issue",
    "credential_issue",
    "certificate_file_generation",
    "file_storage",
    "outbound_communication_send",
    "runtime_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
