export const badgeExportModuleManifest = {
  seed_id: 'seed_6c_119_badge_export',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.badge_export',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Badge export',
  proposed_model_name: 'Phase6CBadgeExport',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.badge_export.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-009', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'source_record_ref',
    'export_format',
    'badge_layout_ref',
    'printable_attendee_refs',
    'review_attendee_refs',
    'row_count',
    'printable_count',
    'review_count',
    'control_metadata',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'file_generation',
    'file_storage',
    'qr_token_creation',
    'ticket_mutation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
