export const checkinTimeWindowModuleManifest = {
  seed_id: "seed_6c_113_checkin_time_window",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.checkin_time_window",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Check-in time-window enforcement",
  proposed_model_name: "Phase6CCheckinTimeWindow",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-003", "6C-ATT-018", "6C-EVENT-CHECK-014", "6C-GLOBAL-018"],
  dependency_refs: ["seed_6a_service_manifest_contract", "6C.08", "6A.08", "6A.11", "6A.14", "6B.06", "seed_6c_001_employee_person_extension"],
  adl_refs: ["ADL-024"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_issue_ref",
    "attempted_checkin_at",
    "window_start_at",
    "window_end_at",
    "timezone",
    "decision",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.checkin_time_window.runtime_evaluated"],
  evidence_artifacts: [
    "checkin_time_window_runtime_receipt",
    "checkin_time_window_validation_result",
    "checkin_time_window_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "checkin_marking",
    "time_override",
    "ticket_mutation",
    "audit_persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
