export const checkinTimeWindowModuleManifest = {
  seed_id: "seed_6c_113_checkin_time_window",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.checkin_time_window",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Check-in time-window enforcement",
  proposed_model_name: "Phase6CCheckinTimeWindow",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-003"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
