export const duplicateCheckinExceptionModuleManifest = {
  seed_id: 'seed_6c_117_duplicate_checkin_exception',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.duplicate_checkin_exception',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Duplicate check-in blocked and recorded as exception',
  proposed_model_name: 'Phase6CDuplicateCheckinException',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.duplicate_checkin_exception.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-007', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'registration_ref',
    'attendee_ref',
    'ticket_ref',
    'session_ref',
    'source_record_ref',
    'checkin_scope',
    'attempted_checkin_ref',
    'attempted_at',
    'attempted_checkpoint_ref',
    'attempted_operator_user_id',
    'duplicate_detected',
    'exception_record_required',
    'manual_review_required',
    'severity',
    'matched_prior_checkin_refs',
    'rejection_reasons',
    'control_metadata',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'duplicate_persistence',
    'checkin_record_creation',
    'ticket_mutation',
    'attendance_persistence',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
