export const eventLeadHandoffEvidenceModuleManifest = {
  seed_id: "seed_6c_123_event_lead_handoff_evidence",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.event_lead_handoff_evidence",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Event lead handoff evidence",
  proposed_model_name: "Phase6CEventLeadHandoffEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-013", "6C-EVENT-REG-012", "6C-GLOBAL-018", "6C-API-008"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_ref",
    "source_record_ref",
    "handoff_source",
    "identity_policy",
    "lead_identity_refs",
    "source_refs",
    "handoff_reason",
    "consent_basis_ref",
    "evidence_payload",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.event_lead_handoff_evidence.runtime_evaluated"],
  external_reference_targets: ["6B.06.crm_owned_handler", "6A.11.evidence_stream", "6A.14.communication_gateway_reference_only"],
  forbidden_behaviors: [
    "direct_crm_write",
    "crm_lead_mutation",
    "outbound_communication_send",
    "runtime_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
