export const feedbackIdentityPolicyModuleManifest = {
  seed_id: 'seed_6c_121_feedback_identity_policy',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.feedback_identity_policy',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Anonymous or identified feedback policy',
  proposed_model_name: 'Phase6CFeedbackIdentityPolicy',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.feedback_identity_policy.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-011', '6C-EVENT-CHECK-013', '6C-EVENT-CHECK-014'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'form_ref',
    'identity_mode',
    'response_is_anonymous',
    'attendee_ref',
    'registration_ref',
    'crm_lead_ref',
    'identity_required',
    'crm_handoff_allowed',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'response_collection',
    'identity_persistence',
    'crm_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
