export const kioskModeCheckinModuleManifest = {
  seed_id: "seed_6c_114_kiosk_mode_checkin",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.kiosk_mode_checkin",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Kiosk-mode check-in",
  proposed_model_name: "Phase6CKioskModeCheckin",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-004", "6C-EVENT-CHECK-014", "6C-GLOBAL-018"],
  dependency_refs: ["seed_6a_service_manifest_contract", "6C.08", "6A.11", "6A.14", "6B.06", "seed_6c_001_employee_person_extension"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "kiosk_session_ref",
    "kiosk_device_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_issue_ref",
    "kiosk_mode_active",
    "token_status",
    "time_window_status",
    "decision",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.kiosk_mode_checkin.runtime_evaluated"],
  evidence_artifacts: [
    "kiosk_mode_checkin_runtime_receipt",
    "kiosk_mode_checkin_validation_result",
    "kiosk_mode_checkin_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "checkin_marking",
    "kiosk_ui_session_creation",
    "device_enrollment",
    "token_override",
    "persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
