export const PHASE_6C_KIOSK_MODE_CHECKIN_SEED_ID = "seed_6c_114_kiosk_mode_checkin" as const;
export const PHASE_6C_KIOSK_MODE_CHECKIN_COMPONENT_ID = "6C.09" as const;
export const KIOSK_MODE_CHECKIN_RUNTIME_EVENT = "phase_6c.events_check_in_and_post_event_service.kiosk_mode_checkin.runtime_evaluated" as const;

export type KioskModeCheckinDecision = 'KIOSK_CHECKIN_ALLOWED' | 'KIOSK_DISABLED' | 'TOKEN_REJECTED' | 'WINDOW_REJECTED' | 'KIOSK_REQUIRES_REVIEW';
export type KioskTokenStatus = 'valid' | 'invalid' | 'expired' | 'missing';
export type KioskWindowStatus = 'allowed' | 'too_early' | 'too_late' | 'review';

export type KioskModeCheckinInput = {
  organization_id: string;
  service_manifest_contract_id: string;
  event_config_ref: string;
  kiosk_session_ref: string;
  kiosk_device_ref: string;
  registration_ref: string;
  attendee_ref: string;
  ticket_issue_ref: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  kiosk_mode_active: boolean;
  token_status: KioskTokenStatus;
  time_window_status: KioskWindowStatus;
  signed_ticket_token_ref?: string;
  checkin_time_window_ref?: string;
  person_identity_ref?: string;
  access_audit_ref?: string;
  crm_event_ref?: string;
  control_metadata?: Record<string, unknown>;
  checkin_mark_requested?: boolean;
  kiosk_ui_session_requested?: boolean;
  device_enrollment_requested?: boolean;
  token_override_requested?: boolean;
  persistence_requested?: boolean;
  schema_mutation_requested?: boolean;
  frontend_requested?: boolean;
};

export type KioskModeCheckinRuntimeReceipt = {
  seed_id: typeof PHASE_6C_KIOSK_MODE_CHECKIN_SEED_ID;
  component_id: typeof PHASE_6C_KIOSK_MODE_CHECKIN_COMPONENT_ID;
  component_slug: "events_check_in_and_post_event_service";
  model_name: "Phase6CKioskModeCheckin";
  event_name: typeof KIOSK_MODE_CHECKIN_RUNTIME_EVENT;
  organization_id: string;
  service_manifest_contract_id: string;
  event_config_ref: string;
  kiosk_session_ref: string;
  kiosk_device_ref: string;
  registration_ref: string;
  attendee_ref: string;
  ticket_issue_ref: string;
  source_record_ref: string;
  kiosk_mode_active: boolean;
  token_status: KioskTokenStatus;
  time_window_status: KioskWindowStatus;
  decision: KioskModeCheckinDecision;
  dependency_trace: {
    service_manifest_contract: string;
    registration_context: '6C.08';
    signed_ticket_token_ref: string | null;
    checkin_time_window_ref: string | null;
    person_identity_ref: string | null;
    access_audit_ref: string | null;
    crm_event_ref: string | null;
  };
  decision_refs: readonly string[];
  forbidden_behavior_rejections: readonly string[];
  control_metadata: Record<string, unknown>;
  evaluated_by_user_id: string;
  evaluated_at: string;
  runtime_evidence_digest: string;
};
