export const manualCheckinOverrideModuleManifest = {
  seed_id: 'seed_6c_116_manual_checkin_override',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.manual_checkin_override',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Manual check-in override with reason and approval',
  proposed_model_name: 'Phase6CManualCheckinOverride',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.manual_checkin_override.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-006', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'registration_ref',
    'attendee_ref',
    'ticket_ref',
    'session_ref',
    'source_record_ref',
    'override_reason',
    'approval_status',
    'approval_ref',
    'approved_by_user_id',
    'requested_by_user_id',
    'eligibility_status',
    'existing_checkin_ref',
    'manual_override_allowed',
    'approval_required',
    'rejection_reasons',
    'control_metadata',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'checkin_record_creation',
    'ticket_mutation',
    'session_capacity_mutation',
    'attendance_persistence',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
