export const offlineCheckinQueueModuleManifest = {
  seed_id: 'seed_6c_118_offline_checkin_queue',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.offline_checkin_queue',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Offline check-in queue',
  proposed_model_name: 'Phase6COfflineCheckinQueue',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.offline_checkin_queue.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-008', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_record_ref',
    'queue_entries',
    'known_synced_entry_refs',
    'accepted_entry_refs',
    'review_entry_refs',
    'rejected_entry_refs',
    'duplicate_entry_refs',
    'expired_entry_refs',
    'sync_state',
    'rejection_reasons',
    'control_metadata',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'queue_persistence',
    'network_sync',
    'checkin_record_creation',
    'ticket_mutation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
