export const postEventResourceFileRefModuleManifest = {
  seed_id: 'seed_6c_122_post_event_resource_file_ref',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.post_event_resource_file_ref',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Post-event resources through file refs',
  proposed_model_name: 'Phase6CPostEventResourceFileRef',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.post_event_resource_file_ref.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-012', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'source_record_ref',
    'resources',
    'ready_file_refs',
    'review_file_refs',
    'resource_count',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'file_upload',
    'file_storage',
    'file_mutation',
    'public_url_generation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
