export const postEventFeedbackFormModuleManifest = {
  seed_id: 'seed_6c_120_post_event_feedback_form',
  component_id: '6C.09',
  component_slug: 'events_check_in_and_post_event_service',
  module_key: 'phase-6c.events-check-in-and-post-event-service',
  capability_surface: 'phase_6c.events_check_in_and_post_event_service.post_event_feedback_form',
  source_system: 'PHASE_6C_V4_FFET_RUNTIME',
  objective: 'Post-event feedback form',
  proposed_model_name: 'Phase6CPostEventFeedbackForm',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  runtime_event: 'phase_6c.events_check_in_and_post_event_service.post_event_feedback_form.runtime_evaluated',
  decision_refs: ['6C-EVENT-CHECK-010', '6C-EVENT-CHECK-014', '6C-EVENT-REG-012'],
  dependency_refs: ['seed_6a_service_manifest_contract', '6C.08'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'event_ref',
    'form_ref',
    'questions',
    'required_question_refs',
    'scoring_question_refs',
    'review_question_refs',
    'allow_anonymous_response',
    'opened_at',
    'closes_at',
    'runtime_evidence_digest',
  ],
  forbidden_behaviors: [
    'form_persistence',
    'response_collection',
    'frontend_screen',
    'schema_mutation',
    'crm_write',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
