export const qrTicketIssuingModuleManifest = {
  seed_id: "seed_6c_111_qr_ticket_issuing",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.qr_ticket_issuing",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "QR ticket issuing from registration/payment state",
  proposed_model_name: "Phase6CQrTicketIssuing",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-001", "6C-EVENT-CHECK-014", "6C-EVENT-REG-012", "6C-GLOBAL-018"],
  dependency_refs: ["seed_6a_service_manifest_contract", "6C.08", "6A.11", "6A.14", "6B.06", "seed_6c_001_employee_person_extension"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_type_ref",
    "registration_state",
    "payment_state",
    "ticket_status",
    "qr_ticket_payload",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.qr_ticket_issuing.runtime_evaluated"],
  evidence_artifacts: [
    "qr_ticket_issuing_runtime_receipt",
    "qr_ticket_issuing_validation_result",
    "qr_ticket_issuing_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "qr_image_render",
    "ticket_delivery",
    "check_in_marking",
    "payment_capture",
    "ticket_persistence",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
