export const PHASE_6C_SESSION_LEVEL_CHECKIN_SEED_ID = "seed_6c_115_session_level_checkin" as const;
export const PHASE_6C_SESSION_LEVEL_CHECKIN_COMPONENT_ID = "6C.09" as const;
export const SESSION_LEVEL_CHECKIN_RUNTIME_EVENT = "phase_6c.events_check_in_and_post_event_service.session_level_checkin.runtime_evaluated" as const;

export type SessionLevelCheckinDecision = 'SESSION_CHECKIN_ALLOWED' | 'ALREADY_CHECKED_IN' | 'SESSION_NOT_ELIGIBLE' | 'WINDOW_REJECTED' | 'SESSION_CHECKIN_REQUIRES_REVIEW';
export type SessionEligibilityStatus = 'eligible' | 'not_registered' | 'capacity_blocked' | 'cancelled' | 'review';
export type SessionWindowStatus = 'allowed' | 'too_early' | 'too_late' | 'review';

export type SessionLevelCheckinInput = {
  organization_id: string;
  service_manifest_contract_id: string;
  event_config_ref: string;
  session_ref: string;
  registration_ref: string;
  attendee_ref: string;
  ticket_issue_ref: string;
  source_record_ref: string;
  evaluated_by_user_id: string;
  evaluated_at: string;
  session_eligibility_status: SessionEligibilityStatus;
  time_window_status: SessionWindowStatus;
  prior_session_checkin_ref?: string;
  signed_ticket_token_ref?: string;
  kiosk_checkin_ref?: string;
  person_identity_ref?: string;
  access_audit_ref?: string;
  crm_event_ref?: string;
  control_metadata?: Record<string, unknown>;
  checkin_record_requested?: boolean;
  session_capacity_mutation_requested?: boolean;
  attendance_persistence_requested?: boolean;
  ticket_mutation_requested?: boolean;
  schema_mutation_requested?: boolean;
  frontend_requested?: boolean;
};

export type SessionLevelCheckinRuntimeReceipt = {
  seed_id: typeof PHASE_6C_SESSION_LEVEL_CHECKIN_SEED_ID;
  component_id: typeof PHASE_6C_SESSION_LEVEL_CHECKIN_COMPONENT_ID;
  component_slug: "events_check_in_and_post_event_service";
  model_name: "Phase6CSessionLevelCheckin";
  event_name: typeof SESSION_LEVEL_CHECKIN_RUNTIME_EVENT;
  organization_id: string;
  service_manifest_contract_id: string;
  event_config_ref: string;
  session_ref: string;
  registration_ref: string;
  attendee_ref: string;
  ticket_issue_ref: string;
  source_record_ref: string;
  session_eligibility_status: SessionEligibilityStatus;
  time_window_status: SessionWindowStatus;
  decision: SessionLevelCheckinDecision;
  dependency_trace: {
    service_manifest_contract: string;
    registration_context: '6C.08';
    prior_session_checkin_ref: string | null;
    signed_ticket_token_ref: string | null;
    kiosk_checkin_ref: string | null;
    person_identity_ref: string | null;
    access_audit_ref: string | null;
    crm_event_ref: string | null;
  };
  decision_refs: readonly string[];
  forbidden_behavior_rejections: readonly string[];
  control_metadata: Record<string, unknown>;
  evaluated_by_user_id: string;
  evaluated_at: string;
  runtime_evidence_digest: string;
};
