export const signedTicketTokenModuleManifest = {
  seed_id: "seed_6c_112_signed_ticket_token",
  component_id: "6C.09",
  component_slug: "events_check_in_and_post_event_service",
  module_key: "phase-6c.events-check-in-and-post-event-service",
  capability_surface: "phase_6c.events_check_in_and_post_event_service.signed_ticket_token",
  source_system: 'PHASE_6C_RUNTIME_FFET_V4',
  objective: "Cryptographic signed ticket tokens",
  proposed_model_name: "Phase6CSignedTicketToken",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-EVENT-CHECK-002", "6C-EVENT-CHECK-014", "6C-GLOBAL-018"],
  dependency_refs: ["seed_6a_service_manifest_contract", "6C.08", "6A.11", "6A.14", "6B.06", "seed_6c_001_employee_person_extension"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "event_config_ref",
    "registration_ref",
    "attendee_ref",
    "ticket_type_ref",
    "qr_payload_digest",
    "signing_key_ref",
    "token",
    "token_header_digest",
    "token_payload_digest",
    "token_signature_digest",
    "runtime_evidence_digest",
  ],
  emitted_events: ["phase_6c.events_check_in_and_post_event_service.signed_ticket_token.runtime_evaluated"],
  evidence_artifacts: [
    "signed_ticket_token_runtime_receipt",
    "signed_ticket_token_validation_result",
    "signed_ticket_token_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "production_secret_lookup",
    "token_persistence",
    "token_delivery",
    "check_in_validation",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
