export const allowanceDeductionFormulaModuleManifest = {
  seed_id: 'seed_6b_14_allowance_deduction_formula',
  component_id: '6B.14',
  capability_surface: 'finance_payroll_foundation.allowance_deduction_formula',
  source_system: 'FINANCE_PAYROLL_FOUNDATION',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_payee_model_required: true,
  phase_6b_payroll_batch_model_required: true,
  phase_6b_payroll_payout_model_required: true,
  person_identity_graph_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'payroll_batch_ref',
    'formula_set_ref',
    'formula_ref',
    'formula_kind',
    'formula_method',
    'person_identity_ref',
    'payee_ref',
    'allowance_total_minor',
    'deduction_total_minor',
    'net_adjustment_minor',
    'formula_evidence_ref',
    'formula_digest',
  ],
  forbidden_behaviors: [
    'payout_creation',
    'tax_calculation',
    'disbursement_file_generation',
    'journal_posting',
    'hr_record_mutation',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
