export const hrEventFeedBoundaryModuleManifest = {
  seed_id: 'seed_6b_14_hr_event_feed_boundary',
  component_id: '6B.14',
  capability_surface: 'finance_payroll_foundation.hr_event_feed_boundary',
  source_system: 'FINANCE_PAYROLL_FOUNDATION',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_payee_model_required: true,
  person_identity_graph_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'feed_ref',
    'hr_event_ref',
    'event_type',
    'person_identity_ref',
    'payee_ref',
    'boundary_action',
    'payroll_boundary_evidence_ref',
    'boundary_digest',
  ],
  forbidden_behaviors: [
    'hr_record_mutation',
    'payroll_calculation',
    'payout_creation',
    'disbursement_file_generation',
    'journal_posting',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
