export const payrollRunStateMachineModuleManifest = {
  seed_id: 'seed_6b_14_payroll_run_state_machine',
  component_id: '6B.14',
  capability_surface: 'finance_payroll_foundation.payroll_run_state_machine',
  source_system: 'FINANCE_PAYROLL_FOUNDATION',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_payroll_batch_model_required: true,
  phase_6b_payroll_payout_model_required: true,
  phase_6b_payee_model_required: true,
  person_identity_graph_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'payroll_batch_ref',
    'initial_state',
    'current_state',
    'transition_ref',
    'transition_reason',
    'actor_user_id',
    'state_machine_evidence_ref',
    'state_machine_digest',
  ],
  forbidden_behaviors: [
    'payout_creation',
    'tax_calculation',
    'formula_calculation',
    'disbursement_file_generation',
    'journal_posting',
    'hr_record_mutation',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
