export const payrollTaxSlabCalculatorModuleManifest = {
  seed_id: 'seed_6b_14_payroll_tax_slab_calculator',
  component_id: '6B.14',
  capability_surface: 'finance_payroll_foundation.payroll_tax_slab_calculator',
  source_system: 'FINANCE_PAYROLL_FOUNDATION',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_payee_model_required: true,
  phase_6b_payroll_batch_model_required: true,
  phase_6b_payroll_payout_model_required: true,
  person_identity_graph_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'payroll_batch_ref',
    'tax_table_ref',
    'slab_ref',
    'person_identity_ref',
    'payee_ref',
    'taxable_pay_minor',
    'tax_amount_minor',
    'net_pay_after_tax_minor',
    'payroll_tax_evidence_ref',
    'payroll_tax_digest',
  ],
  forbidden_behaviors: [
    'payout_creation',
    'disbursement_file_generation',
    'journal_posting',
    'hr_record_mutation',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
