export const expenseApprovalWorkflowModuleManifest = {
  seed_id: 'seed_6b_11_expense_approval_workflow',
  component_id: '6B.11',
  capability_surface: 'expense_purchase_vendor.expense_approval_workflow',
  source_system: 'EXPENSE_PURCHASE_VENDOR',
  activation_lifecycle_required: true,
  tenant_service: true,
  expense_record_authority_required: true,
  person_identity_graph_required: true,
  visual_workflow_builder_required: true,
  approval_capability_gated: true,
  owned_data: [
    'expense_record_ref',
    'expense_record_digest',
    'requester_person_ref',
    'approver_person_ref',
    'approval_workflow_ref',
    'approval_step_ref',
    'decision',
    'decision_reason',
    'approval_evidence_ref',
  ],
  forbidden_behaviors: [
    'vendor_payment_execution',
    'payment_allocation_math',
    'provider_callback_processing',
    'gl_posting',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
