export const expenseRecordAuthorityModuleManifest = {
  seed_id: 'seed_6b_11_expense_record_authority',
  component_id: '6B.11',
  capability_surface: 'expense_purchase_vendor.expense_record_authority',
  source_system: 'EXPENSE_PURCHASE_VENDOR',
  activation_lifecycle_required: true,
  tenant_service: true,
  payment_allocation_balance_required: true,
  person_identity_graph_required: true,
  visual_workflow_builder_required: true,
  approval_capability_gated: true,
  owned_data: [
    'expense_record_ref',
    'expense_number',
    'vendor_record_ref',
    'requester_person_ref',
    'approval_workflow_ref',
    'expense_line_ref',
    'expense_total_minor',
    'receipt_evidence_ref',
    'expense_record_digest',
  ],
  forbidden_behaviors: [
    'payment_allocation_math',
    'vendor_payment_execution',
    'provider_callback_processing',
    'gl_posting',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
