export const purchaseOrderAuthorityModuleManifest = {
  seed_id: 'seed_6b_11_purchase_order_authority',
  component_id: '6B.11',
  capability_surface: 'expense_purchase_vendor.purchase_order_authority',
  source_system: 'EXPENSE_PURCHASE_VENDOR',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_purchase_order_model_required: true,
  vendor_record_authority_required: true,
  payment_allocation_balance_required: true,
  person_identity_graph_required: true,
  visual_workflow_builder_required: true,
  approval_capability_gated: true,
  owned_data: [
    'purchase_order_ref',
    'purchase_order_number',
    'vendor_record_ref',
    'requester_person_ref',
    'approver_person_ref',
    'approval_workflow_ref',
    'purchase_order_line_ref',
    'purchase_order_total_minor',
    'purchase_order_evidence_refs',
    'purchase_order_digest',
  ],
  forbidden_behaviors: [
    'purchase_receipt_creation',
    'vendor_invoice_creation',
    'inventory_receiving',
    'payment_allocation_math',
    'provider_callback_processing',
    'gl_posting',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
