export const vendorRecordAuthorityModuleManifest = {
  seed_id: 'seed_6b_11_vendor_record_authority',
  component_id: '6B.11',
  capability_surface: 'expense_purchase_vendor.vendor_record_authority',
  source_system: 'EXPENSE_PURCHASE_VENDOR',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_vendor_model_required: true,
  payment_allocation_balance_required: true,
  person_identity_graph_required: true,
  visual_workflow_builder_required: true,
  approval_capability_gated: true,
  global_identity_ownership: 'references_only',
  owned_data: [
    'vendor_record_ref',
    'source_seed_id',
    'vendor_legal_name',
    'vendor_display_name',
    'vendor_identity_graph_ref',
    'vendor_record_state',
    'payment_terms_ref',
    'default_currency_code',
    'vendor_evidence_refs',
    'vendor_record_digest',
  ],
  forbidden_behaviors: [
    'global_identity_write',
    'vendor_payment_execution',
    'payment_allocation_math',
    'provider_callback_processing',
    'gl_posting',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
