export const reconciliationMatchingModuleManifest = {
  seed_id: 'seed_6b_13_reconciliation_matching',
  component_id: '6B.13',
  capability_surface: 'banking_reconciliation.reconciliation_matching',
  source_system: 'BANKING_RECONCILIATION',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_reconciliation_candidate_model_required: true,
  bank_transaction_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'match_run_ref',
    'bank_account_ref',
    'bank_transaction_ref',
    'allocation_balance_ref',
    'payment_ref',
    'invoice_ref',
    'receivable_ref',
    'chart_account_ref',
    'score',
    'status',
    'candidate_evidence_ref',
    'reconciliation_matching_digest',
  ],
  forbidden_behaviors: [
    'payment_allocation_math',
    'journal_posting',
    'statement_closure',
    'manual_reconciliation_resolution',
    'provider_callback_processing',
    'credential_handling',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
