export const accessProvisioningGatekeeperEventModuleManifest = {
  seed_id: 'seed_6c_018_access_provisioning_gatekeeper_event',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.access_provisioning_gatekeeper_event',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Access provisioning event routed through Gatekeeper',
  proposed_model_name: 'Phase6CAccessProvisioningGatekeeperEvent',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  always_gatekeeper_required: true,
  gatekeeper_bypass_allowed: false,
  direct_access_grant_allowed: false,
  access_core_mutation_executed_by_this_surface: false,
  decision_refs: ['6C-RECRUIT-010'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'access_provisioning_gatekeeper_event_runtime_receipt',
    'access_provisioning_gatekeeper_event_validation_result',
    'access_provisioning_gatekeeper_event_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'employee_ref',
    'gatekeeper_policy_ref',
    'event_bus_topic',
    'grants',
    'gatekeeper_payload',
    'control_metadata',
    'access_provisioning_gatekeeper_event_evidence_digest',
  ],
  forbidden_behaviors: [
    'gatekeeper_bypass',
    'direct_access_grant',
    'access_core_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
