export const applicantSourceLinkageModuleManifest = {
  seed_id: "seed_6c_011_applicant_source_linkage",
  component_id: "6C.02",
  component_slug: "hr_recruitment_and_onboarding_pipeline",
  module_key: "phase-6c.hr-recruitment-and-onboarding-pipeline",
  capability_surface: "phase_6c.hr_recruitment_and_onboarding_pipeline.applicant_source_linkage",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Applicant source linkage from CRM lead or direct HR form",
  proposed_model_name: "Phase6CApplicantSourceLinkage",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  crm_dependency_condition: "lead_sourced_applicant_active",
  crm_mutation_allowed: false,
  employee_creation_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-RECRUIT-001", "6C-RECRUIT-002", "6C-SCHEMA-006", "6C-NON-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "applicant_ref",
    "source_type",
    "direct_hr_form_ref",
    "crm_lead_ref",
    "crm_pipeline_ref",
    "linkage_evidence_ref",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "crm_lead_creation",
    "crm_lead_mutation",
    "employee_creation",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
