export const applicantDedupLinkageModuleManifest = {
  seed_id: 'seed_6c_022_applicant_dedup_linkage',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.applicant_dedup_linkage',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Applicant duplicate detection using CRM dedup patterns',
  proposed_model_name: 'Phase6CApplicantDedupLinkage',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  crm_dedup_patterns_reused: true,
  retain_and_link_only: true,
  destructive_merge_allowed: false,
  direct_crm_mutation_allowed: false,
  applicant_record_mutation_allowed: false,
  person_identity_graph_mutation_allowed: false,
  decision_refs: ['6C-RECRUIT-014', '6C-RECRUIT-002'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'applicant_dedup_linkage_runtime_receipt',
    'applicant_dedup_linkage_validation_result',
    'applicant_dedup_linkage_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'dedup_pattern_ref',
    'applicant_signals',
    'candidate_refs',
    'dedup_scores',
    'recommended_linkage_refs',
    'control_metadata',
    'applicant_dedup_linkage_evidence_digest',
  ],
  forbidden_behaviors: [
    'destructive_merge',
    'direct_crm_mutation',
    'applicant_record_mutation',
    'person_identity_graph_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
