export const applicantSourceLinkageModuleManifest = {
  seed_id: "seed_6c_011_applicant_source_linkage",
  component_id: "6C.02",
  component_slug: "hr_recruitment_and_onboarding_pipeline",
  module_key: "phase-6c.hr-recruitment-and-onboarding-pipeline",
  capability_surface: "phase_6c.hr_recruitment_and_onboarding_pipeline.applicant_source_linkage",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Applicant source linkage from CRM lead or direct HR form",
  proposed_model_name: "Phase6CApplicantSourceLinkage",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-RECRUIT-001"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
