export const applicantStagedDeletionModuleManifest = {
  seed_id: 'seed_6c_021_applicant_staged_deletion',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.applicant_staged_deletion',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Applicant staged deletion and protection rules',
  proposed_model_name: 'Phase6CApplicantStagedDeletion',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  staged_deletion_required: true,
  immediate_deletion_allowed: false,
  hard_delete_execution_allowed: false,
  refs_events_only: true,
  direct_crm_mutation_allowed: false,
  employee_record_mutation_allowed: false,
  decision_refs: ['6C-RECRUIT-013', '6C-RECRUIT-002', '6C-GLOBAL-018'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'applicant_staged_deletion_runtime_receipt',
    'applicant_staged_deletion_validation_result',
    'applicant_staged_deletion_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'requested_action',
    'previous_stage',
    'resulting_stage',
    'retention_policy_ref',
    'permanent_deletion_not_before',
    'protection_refs',
    'block_reasons',
    'control_metadata',
    'applicant_staged_deletion_evidence_digest',
  ],
  forbidden_behaviors: [
    'immediate_deletion',
    'hard_delete_execution',
    'direct_crm_mutation',
    'employee_record_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
