export const backgroundCheckProviderBoundaryModuleManifest = {
  seed_id: 'seed_6c_019_background_check_provider_boundary',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.background_check_provider_boundary',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Provider-neutral background-check boundary only',
  proposed_model_name: 'Phase6CBackgroundCheckProviderBoundary',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  provider_neutral_boundary_only: true,
  real_provider_allowed: false,
  provider_credentials_allowed: false,
  adapter_execution_allowed: false,
  external_submission_allowed: false,
  sensitive_result_storage_allowed: false,
  decision_refs: ['6C-RECRUIT-011'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'background_check_provider_boundary_runtime_receipt',
    'background_check_provider_boundary_validation_result',
    'background_check_provider_boundary_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'provider_boundary_ref',
    'consent_evidence_ref',
    'scopes',
    'boundary_payload',
    'control_metadata',
    'background_check_provider_boundary_evidence_digest',
  ],
  forbidden_behaviors: [
    'real_background_check_provider_call',
    'provider_credentials_handling',
    'adapter_execution',
    'external_submission',
    'sensitive_result_storage',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
