export const interviewCalendarEventRequestModuleManifest = {
  seed_id: 'seed_6c_014_interview_calendar_event_request',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.interview_calendar_event_request',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Interview calendar request via events when Workspace active',
  proposed_model_name: 'Phase6CInterviewCalendarEventRequest',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  workspace_calendar_condition: 'workspace_calendar_active',
  event_only_fallback_allowed: true,
  direct_calendar_mutation_allowed: false,
  provider_sync_allowed: false,
  external_credentials_allowed: false,
  decision_refs: ['6C-RECRUIT-005'],
  conditional_dependency_refs: ['workspace_calendar_active', 'lead_sourced_applicant_active'],
  evidence_artifacts: [
    'interview_calendar_event_request_runtime_receipt',
    'interview_calendar_event_request_validation_result',
    'interview_calendar_event_request_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'interview_stage_code',
    'event_bus_topic',
    'workspace_calendar_active',
    'workspace_calendar_ref',
    'participants',
    'control_metadata',
    'interview_calendar_event_request_evidence_digest',
  ],
  forbidden_behaviors: [
    'direct_calendar_mutation',
    'provider_calendar_sync',
    'external_provider_credentials',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
