export const offerAcceptanceEmployeeCreationRequestModuleManifest = {
  seed_id: 'seed_6c_016_offer_acceptance_employee_creation_request',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.offer_acceptance_employee_creation_request',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Offer acceptance recommends employee creation as explicit step',
  proposed_model_name: 'Phase6COfferAcceptanceEmployeeCreationRequest',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  acceptance_recommends_employee_creation: true,
  employee_creation_explicit_step_required: true,
  employee_creation_executed_by_this_surface: false,
  employee_record_mutation_allowed: false,
  person_identity_mutation_allowed: false,
  decision_refs: ['6C-RECRUIT-007'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'offer_acceptance_employee_creation_request_runtime_receipt',
    'offer_acceptance_employee_creation_request_validation_result',
    'offer_acceptance_employee_creation_request_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'offer_ref',
    'profile_draft',
    'recommendation_payload',
    'control_metadata',
    'offer_acceptance_employee_creation_request_evidence_digest',
  ],
  forbidden_behaviors: [
    'automatic_employee_creation',
    'employee_record_mutation',
    'person_identity_mutation',
    'access_provisioning_execution',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
