export const offerApprovalWorkflowModuleManifest = {
  seed_id: 'seed_6c_015_offer_approval_workflow',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.offer_approval_workflow',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Configurable offer approval workflow',
  proposed_model_name: 'Phase6COfferApprovalWorkflow',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  configurable_approval_rules_required: true,
  hardcoded_rules_allowed: false,
  access_provisioning_via_gatekeeper: true,
  access_provisioning_executed_by_this_surface: false,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-RECRUIT-006'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'offer_approval_workflow_runtime_receipt',
    'offer_approval_workflow_validation_result',
    'offer_approval_workflow_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'offer_ref',
    'configured_policy_ref',
    'approval_rules',
    'matched_rules',
    'control_metadata',
    'offer_approval_workflow_evidence_digest',
  ],
  forbidden_behaviors: [
    'hardcoded_approval_thresholds',
    'access_provisioning_without_gatekeeper',
    'access_provisioning_execution',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
