export const phase6cOfferDocumentGenerationModuleManifest = {
  seed_id: 'seed_6c_020_offer_document_generation',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.offer_document_generation',
  source_system: 'PHASE_6C_FFET_RUNTIME_IMPLEMENTATION',
  capability_implementation_allowed: true,
  runtime_boundary: 'offer_documents_are_prepared_for_6a_file_service_only',
  event_name: 'phase_6c.hr_recruitment_and_onboarding_pipeline.offer_document_generation.request_ready',
  objective: 'Offer documents through 6A file service',
  proposed_model_name: 'Phase6COfferDocumentGeneration',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  file_service_only: true,
  direct_file_mutation_allowed: false,
  local_file_write_allowed: false,
  non_6a_file_service_allowed: false,
  decision_refs: ['6C-RECRUIT-012', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'applicant_ref',
    'offer_ref',
    'template_ref',
    'file_service_ref',
    'offer_document_generation_request',
    'offer_document_generation_payload',
    'offer_document_generation_evidence_receipt',
    'offer_document_generation_evidence_digest',
  ],
  required_external_refs: [
    'seed_6a_service_manifest_contract',
    'seed_6a_file_service',
    'seed_6c_001_employee_person_identity_anchor',
  ],
  forbidden_behaviors: [
    'local_file_write',
    'direct_6a_file_service_mutation',
    'non_6a_file_service_generation',
    'schema_mutation',
    'phase_6a_runtime_mutation',
    'phase_6b_runtime_mutation',
    'ticket_or_execution_flag_flip',
  ],
  evidence_artifacts: [
    'phase_6c_offer_document_generation_request',
    'phase_6c_offer_document_6a_file_service_payload',
    'phase_6c_offer_document_generation_receipt',
  ],
} as const;

export type Phase6cOfferDocumentGenerationModuleManifest = typeof phase6cOfferDocumentGenerationModuleManifest;
