export const onboardingTaskTemplateModuleManifest = {
  seed_id: 'seed_6c_017_onboarding_task_template',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.onboarding_task_template',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Configurable onboarding task templates',
  proposed_model_name: 'Phase6COnboardingTaskTemplate',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  configurable_templates_required: true,
  hardcoded_template_allowed: false,
  task_instantiation_executed_by_this_surface: false,
  workspace_task_mutation_allowed: false,
  decision_refs: ['6C-RECRUIT-008'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'onboarding_task_template_runtime_receipt',
    'onboarding_task_template_validation_result',
    'onboarding_task_template_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'template_ref',
    'template_version',
    'tasks',
    'normalized_tasks',
    'control_metadata',
    'onboarding_task_template_evidence_digest',
  ],
  forbidden_behaviors: [
    'hardcoded_onboarding_template',
    'task_instantiation',
    'workspace_task_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
