export const recruitmentEvidenceFeedModuleManifest = {
  seed_id: 'seed_6c_023_recruitment_evidence_feed',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.recruitment_evidence_feed',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Recruitment evidence for later performance/optimization',
  proposed_model_name: 'Phase6CRecruitmentEvidenceFeed',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  event_feed_only: true,
  performance_calculation_executed_by_this_surface: false,
  optimization_execution_allowed: false,
  phase_6d_dependency_allowed: false,
  direct_crm_mutation_allowed: false,
  decision_refs: ['6C-RECRUIT-015'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'recruitment_evidence_feed_runtime_receipt',
    'recruitment_evidence_feed_validation_result',
    'recruitment_evidence_feed_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'feed_ref',
    'evidence_events',
    'evidence_refs',
    'type_counts',
    'control_metadata',
    'recruitment_evidence_feed_digest',
  ],
  forbidden_behaviors: [
    'performance_calculation',
    'optimization_execution',
    'phase_6d_write_or_dependency',
    'direct_crm_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
