export const recruitmentStageConfigModuleManifest = {
  seed_id: "seed_6c_012_recruitment_stage_config",
  component_id: "6C.02",
  component_slug: "hr_recruitment_and_onboarding_pipeline",
  module_key: "phase-6c.hr-recruitment-and-onboarding-pipeline",
  capability_surface: "phase_6c.hr_recruitment_and_onboarding_pipeline.recruitment_stage_config",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Configurable recruitment lifecycle stages",
  proposed_model_name: "Phase6CRecruitmentStageConfig",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  fully_configurable_stages: true,
  crm_stage_mutation_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-RECRUIT-003", "6C-SCHEMA-006", "6C-NON-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "stages",
    "stage_counts",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "hardcoded_stage_names",
    "crm_stage_mutation",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
