export const scorecardInterviewFormModuleManifest = {
  seed_id: 'seed_6c_013_scorecard_interview_form',
  component_id: '6C.02',
  component_slug: 'hr_recruitment_and_onboarding_pipeline',
  module_key: 'phase-6c.hr-recruitment-and-onboarding-pipeline',
  capability_surface: 'phase_6c.hr_recruitment_and_onboarding_pipeline.scorecard_interview_form',
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: 'Scorecards and interview forms through Configuration Engine',
  proposed_model_name: 'Phase6CScorecardInterviewForm',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  configuration_engine_required: true,
  fully_configurable_forms: true,
  hardcoded_form_allowed: false,
  crm_stage_mutation_allowed: false,
  schema_mutation_allowed: false,
  phase_6a_mutation_allowed: false,
  phase_6b_mutation_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-RECRUIT-004'],
  conditional_dependency_refs: ['lead_sourced_applicant_active'],
  evidence_artifacts: [
    'scorecard_interview_form_runtime_receipt',
    'scorecard_interview_form_validation_result',
    'scorecard_interview_form_forbidden_behavior_rejection_evidence',
  ],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_seed_id',
    'source_record_ref',
    'configuration_engine_form_ref',
    'form_code',
    'form_version',
    'interview_stage_code',
    'sections',
    'score_bands',
    'control_metadata',
    'scorecard_interview_form_evidence_digest',
  ],
  forbidden_behaviors: [
    'hardcoded_form_definition',
    'crm_stage_mutation',
    'schema_mutation',
    'phase_6a_mutation',
    'phase_6b_mutation',
    'runtime_adapter_execution',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
