export const atRiskRulesEngineModuleManifest = {
  seed_id: "seed_6c_042_at_risk_rules_engine",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.at_risk_rules_engine",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "At-risk rules via Rules Engine",
  proposed_model_name: "Phase6CAtRiskRulesEngine",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-004"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "review_cycle_ref",
    "enabled_rule_count",
    "matched_rule_refs",
    "highest_severity",
    "risk_score",
    "at_risk_rules_engine_evidence_digest",
  ],
  required_evidence_artifacts: [
    "at_risk_rule_evaluation_receipt",
    "matched_rule_evidence",
    "risk_score_evidence",
  ],
  forbidden_behaviors: [
    "employee_status_mutation",
    "notification_send",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
