export const commissionTierAcceleratorModuleManifest = {
  seed_id: "seed_6c_046_commission_tier_accelerator",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.commission_tier_accelerator",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Commission tier accelerator evaluator",
  proposed_model_name: "Phase6CCommissionTierAccelerator",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-006"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "commission_plan_ref",
    "period_ref",
    "currency",
    "attainment_amount",
    "base_commission_amount",
    "selected_tier_id",
    "accelerator_rate_percent",
    "gross_accelerator_amount",
    "payable_accelerator_amount",
    "decision",
    "control_metadata",
    "tier_accelerator_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "crm_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "commission_tier_accelerator_runtime_receipt",
    "qualified_tier_evidence_refs",
    "deterministic_tier_accelerator_digest",
  ],
} as const;
