export const commissionPoolDistributionModuleManifest = {
  seed_id: "seed_6c_047_commission_pool_distribution",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.commission_pool_distribution",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Commission pool distribution surface",
  proposed_model_name: "Phase6CCommissionPoolDistribution",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-006"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "pool_ref",
    "period_ref",
    "currency",
    "pool_amount",
    "distribution_lines",
    "allocated_amount_total",
    "undistributed_amount",
    "decision",
    "control_metadata",
    "pool_distribution_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "crm_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "commission_pool_distribution_runtime_receipt",
    "weighted_distribution_lines",
    "undistributed_pool_evidence",
    "deterministic_pool_distribution_digest",
  ],
} as const;
