export const commissionPayrollBatchEventModuleManifest = {
  seed_id: "seed_6c_048_commission_payroll_batch_event",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.commission_payroll_batch_event",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Approved commission batch event to payroll",
  proposed_model_name: "Phase6CCommissionPayrollBatchEvent",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "payroll_batch_ref",
    "payroll_period_ref",
    "currency",
    "event_sequence",
    "event_payload",
    "approved_payroll_amount_total",
    "decision",
    "control_metadata",
    "payroll_batch_event_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "crm_mutation",
    "event_dispatch",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "commission_payroll_batch_event_runtime_receipt",
    "prepared_payroll_event_payload",
    "review_line_rejection_evidence",
    "deterministic_payroll_batch_event_digest",
  ],
} as const;
