export const commissionClawbackReversalModuleManifest = {
  seed_id: "seed_6c_045_commission_clawback_reversal",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.commission_clawback_reversal",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Commission clawback reversal handler",
  proposed_model_name: "Phase6CCommissionClawbackReversal",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-008"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "reversal_batch_ref",
    "period_ref",
    "currency",
    "planned_reversals",
    "requested_reversal_amount_total",
    "approved_reversal_amount_total",
    "unreversed_requested_amount_total",
    "decision",
    "control_metadata",
    "clawback_reversal_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "crm_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "commission_clawback_reversal_runtime_receipt",
    "planned_reversal_ledger",
    "review_required_reversal_evidence",
    "deterministic_clawback_reversal_digest",
  ],
} as const;
