export const commissionDeferredReleaseModuleManifest = {
  seed_id: "seed_6c_044_commission_deferred_release",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.commission_deferred_release",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Deferred commission release scheduler",
  proposed_model_name: "Phase6CCommissionDeferredRelease",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-006"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "scheduler_run_ref",
    "period_ref",
    "currency",
    "planned_releases",
    "ready_release_count",
    "future_release_count",
    "held_release_count",
    "ready_release_amount",
    "future_release_amount",
    "held_release_amount",
    "next_release_at",
    "decision",
    "control_metadata",
    "release_schedule_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "crm_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "commission_deferred_release_runtime_receipt",
    "planned_release_schedule",
    "held_release_review_evidence",
    "deterministic_release_schedule_digest",
  ],
} as const;
