export const offboardingSagaModuleManifest = {
  seed_id: "seed_6c_051_offboarding_saga",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.offboarding_saga",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Offboarding Saga coordinator",
  proposed_model_name: "Phase6COffboardingSaga",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-011", "6C-ADL-002", "6C-ADL-004"],
  adl_refs: ["ADL-001", "ADL-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "saga_ref",
    "employee_ref",
    "steps",
    "next_step_id",
    "compensation_plan",
    "dlq_routes",
    "decision",
    "control_metadata",
    "offboarding_saga_digest",
  ],
  forbidden_behaviors: [
    "two_phase_commit",
    "external_deprovisioning_execution",
    "payroll_mutation",
    "access_mutation",
    "event_dispatch",
    "dlq_write",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "offboarding_saga_runtime_receipt",
    "no_2pc_saga_plan",
    "compensation_plan_evidence",
    "dlq_route_evidence",
    "deterministic_offboarding_saga_digest",
  ],
} as const;
