export const offboardingWorkspaceRemovalStepModuleManifest = {
  seed_id: "seed_6c_054_offboarding_workspace_removal_step",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.offboarding_workspace_removal_step",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Offboarding Workspace removal step",
  proposed_model_name: "Phase6COffboardingWorkspaceRemovalStep",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-012", "6C-HR-OPS-011", "6C-ADL-002", "6C-ADL-004"],
  adl_refs: ["ADL-001", "ADL-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "offboarding_case_ref",
    "employee_ref",
    "workspace_ref",
    "removal_surface",
    "removal_action",
    "removal_disposition",
    "workspace_removal_evidence_digest",
  ],
  emitted_events: ["phase_6c.hr_performance_commission_policy_and_offboarding.offboarding_workspace_removal_step.evaluated"],
  evidence_artifacts: [
    "offboarding_workspace_removal_step_runtime_receipt",
    "offboarding_workspace_removal_step_validation_result",
    "offboarding_workspace_removal_step_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "access_mutation",
    "account_disable_execution",
    "event_dispatch_execution",
    "dlq_write_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
