export const offboardingSettlementStepModuleManifest = {
  seed_id: "seed_6c_052_offboarding_settlement_step",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.offboarding_settlement_step",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Offboarding final settlement step",
  proposed_model_name: "Phase6COffboardingSettlementStep",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-012", "6C-HR-OPS-011", "6C-ADL-002", "6C-ADL-004"],
  adl_refs: ["ADL-001", "ADL-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "saga_ref",
    "settlement_ref",
    "employee_ref",
    "currency",
    "prepared_lines",
    "earning_total",
    "deduction_total",
    "hold_total",
    "net_settlement_amount",
    "decision",
    "control_metadata",
    "settlement_step_digest",
  ],
  forbidden_behaviors: [
    "payroll_mutation",
    "payment_mutation",
    "event_dispatch",
    "dlq_write",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "offboarding_settlement_step_runtime_receipt",
    "settlement_line_evidence",
    "review_required_settlement_evidence",
    "deterministic_settlement_step_digest",
  ],
} as const;
