export const policyVersionLibraryModuleManifest = {
  seed_id: "seed_6c_049_policy_version_library",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.policy_version_library",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Versioned policy library",
  proposed_model_name: "Phase6CPolicyVersionLibrary",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-009"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "library_ref",
    "effective_at",
    "requested_policy_keys",
    "selections",
    "selected_policy_count",
    "missing_policy_count",
    "conflict_policy_count",
    "decision",
    "control_metadata",
    "policy_library_digest",
  ],
  forbidden_behaviors: [
    "policy_mutation",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "policy_version_library_runtime_receipt",
    "effective_policy_selection_evidence",
    "policy_version_conflict_evidence",
    "deterministic_policy_library_digest",
  ],
} as const;
