export const policyAcknowledgementEvidenceModuleManifest = {
  seed_id: "seed_6c_050_policy_acknowledgement_evidence",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.policy_acknowledgement_evidence",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Immutable policy acknowledgement evidence",
  proposed_model_name: "Phase6CPolicyAcknowledgementEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-010"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "acknowledgement_ref",
    "employee_ref",
    "policy_key",
    "policy_version",
    "policy_hash",
    "acknowledgement_channel",
    "acknowledged_at",
    "statement_text_hash",
    "canonical_payload_hash",
    "acknowledgement_evidence_digest",
  ],
  forbidden_behaviors: [
    "policy_mutation",
    "acknowledgement_overwrite",
    "acknowledgement_delete",
    "schema_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "ticket_flag_flip",
  ],
  evidence_artifacts: [
    "policy_acknowledgement_evidence_runtime_receipt",
    "canonical_acknowledgement_payload_hash",
    "immutable_acknowledgement_digest",
  ],
} as const;
