export const weightedGoalReviewCycleModuleManifest = {
  seed_id: "seed_6c_041_weighted_goal_review_cycle",
  component_id: "6C.04",
  component_slug: "hr_performance_commission_policy_and_offboarding",
  module_key: "phase-6c.hr-performance-commission-policy-and-offboarding",
  capability_surface: "phase_6c.hr_performance_commission_policy_and_offboarding.weighted_goal_review_cycle",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Weighted goals and review cycles",
  proposed_model_name: "Phase6CWeightedGoalReviewCycle",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-OPS-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_ref",
    "framework_ref",
    "review_cycle_ref",
    "goal_count",
    "total_weight_percent",
    "weighted_score_percent",
    "completion_percent",
    "weighted_goal_review_cycle_evidence_digest",
  ],
  required_evidence_artifacts: [
    "weighted_goal_review_cycle_receipt",
    "goal_weight_evidence",
    "review_score_evidence",
  ],
  forbidden_behaviors: [
    "score_mutation",
    "commission_mutation",
    "provider_specific_adapter_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
