export const chartOfAccountsModuleManifest = {
  seed_id: 'seed_6b_12_chart_of_accounts',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.chart_of_accounts',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_chart_of_account_model_required: true,
  invoice_record_authority_required: true,
  payment_allocation_balance_required: true,
  expense_record_authority_required: true,
  accounting_periods_protected: true,
  owned_data: [
    'chart_version_ref',
    'account_ref',
    'account_code',
    'account_name',
    'account_type',
    'normal_balance',
    'posting_policy',
    'finance_event_mappings',
    'chart_of_accounts_digest',
  ],
  forbidden_behaviors: [
    'journal_posting',
    'period_close',
    'tax_report_generation',
    'payment_allocation_math',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
