export const financialReportingPackModuleManifest = {
  seed_id: 'seed_6b_12_financial_reporting_pack',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.financial_reporting_pack',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  invoice_record_authority_required: true,
  payment_allocation_balance_required: true,
  expense_record_authority_required: true,
  accounting_periods_protected: true,
  owned_data: [
    'reporting_pack_ref',
    'accounting_period_ref',
    'trial_balance_lines',
    'asset_total_minor',
    'liability_total_minor',
    'equity_total_minor',
    'revenue_total_minor',
    'expense_total_minor',
    'net_income_minor',
    'reporting_pack_digest',
  ],
  forbidden_behaviors: [
    'frontend_screen_creation',
    'external_publication',
    'journal_posting',
    'period_close',
    'payment_allocation_math',
    'schema_mutation',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
