export const fxGainLossAccountingModuleManifest = {
  seed_id: 'seed_6b_12_fx_gain_loss_accounting',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.fx_gain_loss_accounting',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  payment_allocation_balance_required: true,
  journal_entry_engine_required: true,
  invoice_record_authority_supported: true,
  expense_record_authority_supported: true,
  accounting_periods_protected: true,
  adl_refs: ['ADL-016'],
  owned_data: [
    'fx_event_ref',
    'source_document_ref',
    'position_type',
    'original_base_amount_minor',
    'settlement_base_amount_minor',
    'fx_gain_loss_amount_minor',
    'fx_gain_loss_classification',
    'fx_adjustment_lines',
    'fx_gain_loss_digest',
  ],
  forbidden_behaviors: [
    'direct_journal_posting',
    'payment_allocation_math',
    'provider_callback_processing',
    'tax_report_generation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
