export const journalEntryEngineModuleManifest = {
  seed_id: 'seed_6b_12_journal_entry_engine',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.journal_entry_engine',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  core_microservice: true,
  phase_6b_journal_entry_model_required: true,
  phase_6b_journal_entry_line_model_required: true,
  chart_of_accounts_required: true,
  invoice_record_authority_required: true,
  payment_allocation_balance_required: true,
  expense_record_authority_required: true,
  accounting_periods_protected: true,
  adl_refs: ['ADL-016'],
  owned_data: [
    'journal_entry_ref',
    'journal_entry_line_ref',
    'chart_of_account_ref',
    'accounting_period_ref',
    'source_event_name',
    'source_event_ref',
    'debit_total_minor',
    'credit_total_minor',
    'fx_gain_loss_amount_minor',
    'journal_entry_digest',
  ],
  forbidden_behaviors: [
    'period_close',
    'tax_report_generation',
    'payment_allocation_math',
    'provider_callback_processing',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
