export const periodCloseManagementModuleManifest = {
  seed_id: 'seed_6b_12_period_close_management',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.period_close_management',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_accounting_period_model_required: true,
  invoice_record_authority_required: true,
  payment_allocation_balance_required: true,
  expense_record_authority_required: true,
  accounting_periods_protected: true,
  owned_data: [
    'accounting_period_ref',
    'period_start_at',
    'period_end_at',
    'journal_entry_evidence_refs',
    'period_close_evidence_refs',
    'period_close_digest',
  ],
  forbidden_behaviors: [
    'journal_posting',
    'tax_report_generation',
    'payment_allocation_math',
    'retrospective_mutation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
