export const taxMappingReportingModuleManifest = {
  seed_id: 'seed_6b_12_tax_mapping_reporting',
  component_id: '6B.12',
  capability_surface: 'general_ledger_accounting.tax_mapping_reporting',
  source_system: 'GENERAL_LEDGER_ACCOUNTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_tax_mapping_model_required: true,
  invoice_record_authority_required: true,
  payment_allocation_balance_required: true,
  expense_record_authority_required: true,
  accounting_periods_protected: true,
  adl_refs: ['ADL-018'],
  owned_data: [
    'tax_report_ref',
    'tax_mapping_ref',
    'tax_code_ref',
    'tax_rate_basis_points',
    'rounding_mode',
    'taxable_line_ref',
    'tax_amount_minor',
    'tax_report_digest',
  ],
  forbidden_behaviors: [
    'external_tax_filing',
    'journal_posting',
    'period_close',
    'payment_allocation_math',
    'provider_callback_processing',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
