export const paymentAllocationBalanceModuleManifest = {
  seed_id: 'seed_6b_10_payment_allocation_balance',
  component_id: '6B.10',
  capability_surface: 'payment_collection_topup.payment_allocation_balance',
  source_system: 'PAYMENT_COLLECTION_TOPUP',
  activation_lifecycle_required: true,
  core_microservice: true,
  invoice_record_authority_required: true,
  invoice_record_authority_adl_ref: 'ADL-013',
  pricing_table_effective_dates_required: true,
  api_key_scope_required: false,
  provider_neutral: true,
  owned_data: [
    'payment_receipt_ref',
    'payment_evidence_ref',
    'allocation_line_ref',
    'invoice_record_ref',
    'receivable_ref',
    'allocation_amount_minor',
    'invoice_remaining_balance_minor',
    'unallocated_payment_balance_minor',
  ],
  forbidden_behaviors: [
    'provider_callback_processing',
    'provider_api_key_consumption',
    'provider_dispatch',
    'automatic_reconciliation',
    'refund_execution',
    'top_up_execution',
    'invoice_mutation',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
