export const refundToOriginalMethodModuleManifest = {
  seed_id: 'seed_6b_10_refund_to_original_method',
  component_id: '6B.10',
  capability_surface: 'payment_collection_topup.refund_to_original_method',
  source_system: 'PAYMENT_COLLECTION_TOPUP',
  activation_lifecycle_required: true,
  tenant_service: true,
  invoice_record_authority_required: true,
  pricing_table_effective_dates_required: true,
  api_key_scope_required: true,
  original_method_required: true,
  owned_data: [
    'refund_request_ref',
    'payment_receipt_ref',
    'payment_evidence_ref',
    'original_provider_ref',
    'original_payment_method_ref',
    'refund_reason',
    'refund_amount_minor',
    'remaining_refundable_minor',
    'provider_refund_evidence_ref',
  ],
  forbidden_behaviors: [
    'alternate_refund_method',
    'live_provider_dispatch',
    'provider_callback_processing',
    'payment_allocation_math',
    'automatic_reconciliation',
    'top_up_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
