export const topUpPrepaidCreditModuleManifest = {
  seed_id: 'seed_6b_10_top_up_prepaid_credit',
  component_id: '6B.10',
  capability_surface: 'payment_collection_topup.top_up_prepaid_credit',
  source_system: 'PAYMENT_COLLECTION_TOPUP',
  activation_lifecycle_required: true,
  core_microservice: true,
  invoice_record_authority_required: true,
  pricing_table_effective_dates_required: true,
  api_key_scope_required: true,
  prepaid_balance_source_of_truth: true,
  owned_data: [
    'prepaid_account_ref',
    'payment_receipt_ref',
    'payment_evidence_ref',
    'provider_transaction_evidence_ref',
    'current_prepaid_balance_minor',
    'top_up_amount_minor',
    'new_prepaid_balance_minor',
    'top_up_credit_evidence_ref',
  ],
  forbidden_behaviors: [
    'live_provider_dispatch',
    'provider_callback_processing',
    'payment_allocation_math',
    'automatic_reconciliation',
    'refund_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
