export const crmActivityTimelineModuleManifest = {
  seed_id: 'seed_6b_06_crm_activity_timeline',
  component_id: '6B.06',
  capability_surface: 'crm_pipeline.crm_activity_timeline',
  source_system: 'CRM_PIPELINE',
  activation_lifecycle_required: true,
  unified_lead_record_authority_required: true,
  match_candidate_generation_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'timeline_entry_id',
    'lead_record_authority_id',
    'activity_type',
    'activity_direction',
    'occurred_at',
    'recorded_at',
    'timeline_order',
    'source_event_ref',
    'evidence_refs',
  ],
  forbidden_behaviors: [
    'note_creation',
    'stage_history_mutation',
    'communication_send',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
