export const expectedValuePricingBridgeModuleManifest = {
  seed_id: 'seed_6b_06_expected_value_pricing_bridge',
  component_id: '6B.06',
  capability_surface: 'crm_pipeline.expected_value_pricing_bridge',
  source_system: 'CRM_PIPELINE',
  activation_lifecycle_required: true,
  unified_lead_record_authority_required: true,
  match_candidate_generation_required: true,
  visual_workflow_builder_required: true,
  product_price_history_required: true,
  owned_data: [
    'expected_value_bridge_id',
    'lead_record_authority_id',
    'pipeline_stage_key',
    'product_ref',
    'product_price_history_ref',
    'currency_code',
    'unit_price_minor_units',
    'quantity',
    'probability_basis_points',
    'expected_value_minor_units_numerator',
  ],
  forbidden_behaviors: [
    'pricing_engine_execution',
    'price_selection_override',
    'invoice_creation',
    'payment_allocation',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
