export const internalNotesCommentsModuleManifest = {
  seed_id: 'seed_6b_06_internal_notes_comments',
  component_id: '6B.06',
  capability_surface: 'crm_pipeline.internal_notes_comments',
  source_system: 'CRM_PIPELINE',
  activation_lifecycle_required: true,
  unified_lead_record_authority_required: true,
  match_candidate_generation_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'note_id',
    'thread_id',
    'parent_note_id',
    'lead_record_authority_id',
    'timeline_entry_ref',
    'note_kind',
    'visibility',
    'body',
    'mentioned_user_ids',
    'evidence_refs',
  ],
  forbidden_behaviors: [
    'external_communication_send',
    'timeline_entry_creation',
    'stage_history_mutation',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
