export const pipelineStageModelModuleManifest = {
  seed_id: 'seed_6b_06_pipeline_stage_model',
  component_id: '6B.06',
  capability_surface: 'crm_pipeline.pipeline_stage_model',
  source_system: 'CRM_PIPELINE',
  activation_lifecycle_required: true,
  unified_lead_record_authority_required: true,
  match_candidate_generation_required: true,
  visual_workflow_builder_required: true,
  owned_data: [
    'pipeline_stage_model_id',
    'lifecycle_config_ref',
    'stage_id',
    'stage_key',
    'sort_order',
    'allowed_next_stage_keys',
    'stage_history_required',
    'timeline_evidence_required',
  ],
  forbidden_behaviors: [
    'stage_movement_execution',
    'timeline_entry_creation',
    'activity_note_creation',
    'merge_decision_execution',
    'provider_callback_processing',
    'credential_material_storage',
    'frontend_screen',
    'shared_scaffold_mutation',
  ],
} as const;
