export const documentFolderFileRefModuleManifest = {
  seed_id: "seed_6c_077_document_folder_file_ref",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.document_folder_file_ref",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Document folder and file refs",
  proposed_model_name: "Phase6CDocumentFolderFileRef",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-009"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
