export const documentFolderFileRefModuleManifest = {
  seed_id: "seed_6c_077_document_folder_file_ref",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.document_folder_file_ref",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Document folder and file refs",
  proposed_model_name: "Phase6CDocumentFolderFileRef",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-009"],
  file_service_boundary: "6A_FILE_SERVICE_ONLY",
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "workspace_ref",
    "project_ref",
    "folder_ref",
    "parent_folder_ref",
    "file_ref",
    "file_service_ref",
    "display_name",
    "mime_type",
    "size_bytes",
    "checksum_sha256",
    "evidence_refs",
    "document_folder_file_ref_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_document_folder_and_file_refs",
    "validate_folder_tree_has_no_cycles",
    "validate_files_reference_existing_folders",
    "enforce_6a_file_service_only_boundary",
    "produce_deterministic_document_folder_file_ref_evidence_digest"
  ],
  forbidden_behaviors: [
    "file_upload",
    "file_binary_read",
    "storage_mutation",
    "external_provider_call",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
