export const projectTemplateModuleManifest = {
  seed_id: 'seed_6c_080_project_template',
  component_id: '6C.06',
  component_slug: 'workspace_tasks_projects_documents_and_knowledge',
  module_key: 'phase-6c.workspace-tasks-projects-documents-and-knowledge',
  capability_surface: 'phase_6c.workspace_tasks_projects_documents_and_knowledge.project_template',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Configurable project templates',
  proposed_model_name: 'Phase6CProjectTemplate',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  tenant_authored_template_required: true,
  hardcoded_template_forbidden: true,
  decision_refs: ['6C-WORK-TASK-012', '6C-WORK-TASK-013', '6C-GLOBAL-018', '6C-WORK-TASK-005', '6C-WORK-TASK-006'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'template_ref',
    'template_name',
    'version',
    'status',
    'visibility',
    'authored_by_user_id',
    'phases',
    'task_blueprints',
    'variable_definitions',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_tasks_projects_documents_and_knowledge.project_template.runtime_evaluated'],
  evidence_artifacts: [
    'project_template_runtime_receipt',
    'project_template_validation_result',
    'project_template_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'hardcoded_template',
    'platform_default_template_without_tenant_author',
    'project_creation_execution',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
