export const projectRecordModuleManifest = {
  seed_id: "seed_6c_072_project_record",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.project_record",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Project record and metadata",
  proposed_model_name: "Phase6CProjectRecord",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-004"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "project_ref",
    "name",
    "summary",
    "status",
    "priority",
    "visibility",
    "owner_user_ref",
    "sponsor_user_ref",
    "team_refs",
    "workspace_ref",
    "start_at",
    "target_end_at",
    "completed_at",
    "parent_project_ref",
    "dependency_refs",
    "budget_ref",
    "tags",
    "metadata_entries",
    "evidence_refs",
    "project_record_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_project_record_metadata",
    "validate_project_status_timeline_consistency",
    "capture_dependency_references_without_executing_graph",
    "produce_deterministic_project_record_evidence_digest"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "dependency_graph_execution",
    "gantt_view_rendering",
    "notification_send",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
