export const projectDependencyEngineModuleManifest = {
  seed_id: "seed_6c_073_project_dependency_engine",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.project_dependency_engine",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Project dependency engine without UI Gantt",
  proposed_model_name: "Phase6CProjectDependencyEngine",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-004"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "graph_ref",
    "project_ref",
    "dependency_ref",
    "source_project_ref",
    "target_project_ref",
    "dependency_type",
    "lag_days",
    "is_blocking",
    "topological_order",
    "dependency_depth_by_project",
    "cycle_paths",
    "evidence_refs",
    "project_dependency_engine_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_project_dependency_graph",
    "detect_missing_self_and_duplicate_dependency_edges",
    "detect_project_dependency_cycles_with_dfs",
    "produce_topological_order_without_gantt_ui",
    "produce_deterministic_project_dependency_engine_evidence_digest"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "gantt_view_rendering",
    "frontend_screen",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "notification_send",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
