export const projectBudgetEvidenceRefModuleManifest = {
  seed_id: "seed_6c_074_project_budget_evidence_ref",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.project_budget_evidence_ref",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Read-only 6B Finance budget evidence refs",
  proposed_model_name: "Phase6CProjectBudgetEvidenceRef",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-005", "6C-WORK-TASK-006"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "project_ref",
    "budget_context_ref",
    "evidence_ref",
    "finance_source_ref",
    "evidence_type",
    "amount_minor_units",
    "currency_code",
    "captured_at",
    "read_model_version",
    "project_budget_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_read_only_6b_finance_budget_evidence_refs",
    "validate_budget_evidence_amount_currency_pairing",
    "reject_finance_write_allocation_payment_and_reconciliation_requests",
    "produce_deterministic_project_budget_evidence_digest"
  ],
  forbidden_behaviors: [
    "finance_write",
    "budget_allocation",
    "payment_posting",
    "reconciliation_execution",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
