export const taskProjectCalendarEventModuleManifest = {
  seed_id: 'seed_6c_082_task_project_calendar_event',
  component_id: '6C.06',
  component_slug: 'workspace_tasks_projects_documents_and_knowledge',
  module_key: 'phase-6c.workspace-tasks-projects-documents-and-knowledge',
  capability_surface: 'phase_6c.workspace_tasks_projects_documents_and_knowledge.task_project_calendar_event',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Task/project events consumable by Calendar',
  proposed_model_name: 'Phase6CTaskProjectCalendarEvent',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  calendar_consumption_payload_only: true,
  direct_calendar_write_forbidden: true,
  decision_refs: ['6C-WORK-TASK-015', '6C-CAL-001', '6C-CAL-002', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'source_type',
    'source_ref',
    'event_ref',
    'event_kind',
    'calendar_payload',
    'event_uid',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_tasks_projects_documents_and_knowledge.task_project_calendar_event.runtime_evaluated'],
  evidence_artifacts: [
    'task_project_calendar_event_runtime_receipt',
    'task_project_calendar_event_validation_result',
    'task_project_calendar_event_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'calendar_write_execution',
    'external_provider_sync',
    'direct_calendar_mutation',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
