export const taskRecordModuleManifest = {
  seed_id: "seed_6c_070_task_record",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.task_record",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Task record with full task fields",
  proposed_model_name: "Phase6CTaskRecord",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-002"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "task_ref",
    "title",
    "description",
    "status",
    "priority",
    "visibility",
    "owner_user_ref",
    "assignee_user_refs",
    "watcher_user_refs",
    "team_refs",
    "workspace_ref",
    "project_ref",
    "parent_task_ref",
    "external_ref",
    "start_at",
    "due_at",
    "completed_at",
    "blocked_reason",
    "tags",
    "evidence_refs",
    "task_record_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_full_task_record_fields",
    "validate_task_status_timeline_consistency",
    "evaluate_assignment_and_visibility_review_reasons",
    "produce_deterministic_task_record_evidence_digest"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "notification_send",
    "workflow_transition_execution",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
