export const taskReminderGatewayModuleManifest = {
  seed_id: 'seed_6c_079_task_reminder_gateway',
  component_id: '6C.06',
  component_slug: 'workspace_tasks_projects_documents_and_knowledge',
  module_key: 'phase-6c.workspace-tasks-projects-documents-and-knowledge',
  capability_surface: 'phase_6c.workspace_tasks_projects_documents_and_knowledge.task_reminder_gateway',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Task reminders through gateway',
  proposed_model_name: 'Phase6CTaskReminderGateway',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  gateway_routing_required: true,
  opt_out_enforcement_required: true,
  adl_refs: ['ADL-004'],
  decision_refs: ['6C-GLOBAL-013', '6C-ADL-008', '6C-GLOBAL-018', '6C-WORK-TASK-005', '6C-WORK-TASK-006'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'reminder_ref',
    'task_ref',
    'task_title',
    'due_at',
    'reminder_at',
    'recipient_refs',
    'gateway_policy_refs',
    'idempotency_key',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_tasks_projects_documents_and_knowledge.task_reminder_gateway.runtime_evaluated'],
  evidence_artifacts: [
    'task_reminder_gateway_runtime_receipt',
    'task_reminder_gateway_validation_result',
    'task_reminder_gateway_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'direct_provider_send',
    'gateway_bypass',
    'opt_out_bypass',
    'message_delivery_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
