export const taskStatusConfigModuleManifest = {
  seed_id: "seed_6c_071_task_status_config",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.task_status_config",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Configurable task status with hard anchors",
  proposed_model_name: "Phase6CTaskStatusConfig",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-003"],
  hard_anchors: ["OPEN", "IN_PROGRESS", "DONE"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "config_ref",
    "allow_custom_status_labels",
    "required_hard_anchors",
    "status_key",
    "label",
    "category",
    "sort_order",
    "is_enabled",
    "is_default",
    "hard_anchor",
    "requires_reason",
    "allowed_next_status_keys",
    "evidence_refs",
    "task_status_config_evidence_digest"
  ],
  runtime_behaviors: [
    "validate_minimal_hard_status_anchors",
    "normalize_configurable_task_status_labels",
    "validate_status_transition_targets",
    "produce_deterministic_task_status_config_evidence_digest"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "workflow_transition_execution",
    "notification_send",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
