export const tenantAuthoredKnowledgeModuleManifest = {
  seed_id: 'seed_6c_081_tenant_authored_knowledge',
  component_id: '6C.06',
  component_slug: 'workspace_tasks_projects_documents_and_knowledge',
  module_key: 'phase-6c.workspace-tasks-projects-documents-and-knowledge',
  capability_surface: 'phase_6c.workspace_tasks_projects_documents_and_knowledge.tenant_authored_knowledge',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Tenant-authored knowledge pages',
  proposed_model_name: 'Phase6CTenantAuthoredKnowledge',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  tenant_authored_content_required: true,
  hardcoded_content_forbidden: true,
  decision_refs: ['6C-WORK-TASK-013', '6C-WORK-TASK-007', '6C-WORK-TASK-008', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'page_ref',
    'page_slug',
    'title',
    'status',
    'visibility',
    'authored_by_user_id',
    'version',
    'blocks',
    'content_sha256',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_tasks_projects_documents_and_knowledge.tenant_authored_knowledge.runtime_evaluated'],
  evidence_artifacts: [
    'tenant_authored_knowledge_runtime_receipt',
    'tenant_authored_knowledge_validation_result',
    'tenant_authored_knowledge_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'hardcoded_content',
    'platform_default_content_without_tenant_author',
    'publish_without_tenant_author',
    'persistence_execution',
    'realtime_collaboration_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
