export const timeLogEvidenceModuleManifest = {
  seed_id: "seed_6c_078_time_log_evidence",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.time_log_evidence",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Time log evidence for future billing dimensions",
  proposed_model_name: "Phase6CTimeLogEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-010"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "time_log_ref",
    "subject_user_ref",
    "project_ref",
    "task_ref",
    "work_type",
    "billing_dimension_state",
    "billing_dimension_refs",
    "start_at",
    "end_at",
    "duration_minutes",
    "evidence_refs",
    "time_log_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_time_log_evidence_entries",
    "validate_time_log_duration_against_timestamps",
    "calculate_future_billing_candidate_minutes_without_billing_write",
    "produce_deterministic_time_log_evidence_digest"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "invoice_generation",
    "payroll_write",
    "finance_write",
    "timer_adapter_invocation",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
