export const wikiPageVersioningModuleManifest = {
  seed_id: "seed_6c_075_wiki_page_versioning",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.wiki_page_versioning",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Wiki page version history",
  proposed_model_name: "Phase6CWikiPageVersioning",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-007", "6C-WORK-TASK-008"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "page_ref",
    "version_number",
    "title",
    "content_hash",
    "author_user_ref",
    "created_at",
    "change_type",
    "change_summary",
    "published",
    "restored_from_version_number",
    "restore_candidate_version_number",
    "restore_candidate_available",
    "evidence_refs",
    "wiki_page_versioning_evidence_digest"
  ],
  runtime_behaviors: [
    "normalize_wiki_page_version_history",
    "validate_monotonic_version_numbers_and_timestamps",
    "compute_version_content_hashes",
    "evaluate_restore_candidate_without_executing_restore",
    "reject_realtime_collaboration_and_frontend_editor_requests"
  ],
  forbidden_behaviors: [
    "database_persistence",
    "restore_execution",
    "realtime_collaboration",
    "frontend_editor_publication",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
