export const wikiRestoreModuleManifest = {
  seed_id: "seed_6c_076_wiki_restore",
  component_id: "6C.06",
  component_slug: "workspace_tasks_projects_documents_and_knowledge",
  module_key: "phase-6c.workspace-tasks-projects-documents-and-knowledge",
  capability_surface: "phase_6c.workspace_tasks_projects_documents_and_knowledge.wiki_restore",
  source_system: "PHASE_6C_FFET_RUNTIME",
  objective: "Wiki/document restore rules",
  proposed_model_name: "Phase6CWikiRestore",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-TASK-014"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "page_ref",
    "current_version_number",
    "target_version_number",
    "restore_mode",
    "restore_reason",
    "requested_by_user_ref",
    "reviewer_user_ref",
    "version_snapshots",
    "evidence_refs",
    "wiki_restore_evidence_digest"
  ],
  runtime_behaviors: [
    "evaluate_customer_first_restore_eligibility",
    "require_non_destructive_create_new_version_restore_mode",
    "validate_restore_target_and_current_version_snapshots",
    "produce_deterministic_wiki_restore_evidence_digest"
  ],
  forbidden_behaviors: [
    "restore_execution",
    "database_persistence",
    "overwrite_current_version",
    "history_deletion",
    "frontend_screen",
    "runtime_adapter_execution",
    "schema_mutation",
    "cross_phase_write",
    "shared_scaffold_mutation",
    "ticket_flag_flip"
  ]
} as const;
