export const customerBillingOperationsModuleManifest = {
  seed_id: 'seed_6b_15_customer_billing_operations',
  component_id: '6B.15',
  capability_surface: 'finance_billing_operations.customer_billing_operations',
  source_system: 'FINANCE_BILLING_OPERATIONS',
  activation_lifecycle_required: true,
  tenant_service: true,
  phase_6b_billing_operation_model_required: true,
  phase_6b_budget_cap_model_required: true,
  pricing_table_effective_dates_required: true,
  optimization_fact_store_required: true,
  payment_allocation_balance_required: true,
  chart_of_accounts_required: true,
  owned_data: [
    'billing_operations_ref',
    'customer_account_ref',
    'service_ref',
    'pricing_table_ref',
    'optimization_fact_ref',
    'budget_cap_ref',
    'total_spend_minor',
    'budget_cap_breach_count',
    'operation_evidence_ref',
    'operation_digest',
  ],
  forbidden_behaviors: [
    'invoice_generation',
    'proration_calculation',
    'dunning_action',
    'payment_collection',
    'journal_posting',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
