export const announcementGatewayModuleManifest = {
  seed_id: 'seed_6c_088_announcement_gateway',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.announcement_gateway',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Announcements through Communication Gateway',
  proposed_model_name: 'Phase6CAnnouncementGateway',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-006', '6C-CAL-007', '6C-GLOBAL-013', '6C-ADL-008', '6C-ADL-009', '6C-GLOBAL-018'],
  adl_refs: ['ADL-004'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'announcement_id',
    'source_record_ref',
    'notice_class',
    'audience_segments',
    'gateway_policy_ref',
    'idempotency_key',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'normalize_announcement_gateway_request',
    'route_announcements_through_communication_gateway',
    'enforce_global_opt_out_for_non_mandatory_announcements',
    'apply_gateway_routed_mandatory_notice_opt_out_exemption',
    'produce_delivery_intent_receipts_without_provider_execution',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.announcement_gateway.runtime_evaluated'],
  external_dependencies: [
    {
      target: '6A.11',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-004'],
      reason: 'All outbound announcement delivery must route through the Communication Gateway with global opt-out enforcement.',
    },
  ],
  forbidden_behaviors: [
    'direct_provider_send',
    'gateway_bypass',
    'manual_opt_out_bypass',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
