export const announcementAckEvidenceModuleManifest = {
  seed_id: 'seed_6c_095_announcement_ack_evidence',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.announcement_ack_evidence',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Announcement acknowledgement evidence',
  proposed_model_name: 'Phase6CAnnouncementAckEvidence',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-014', '6C-GLOBAL-013', '6C-ADL-008', '6C-GLOBAL-018'],
  adl_refs: ['ADL-004'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'announcement_id',
    'delivery_intent_id',
    'recipient_user_id',
    'acknowledgement_status',
    'source_ack_ref',
    'gateway_policy_ref',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'normalize_announcement_acknowledgement_evidence',
    'classify_acknowledged_pending_not_required_or_declined',
    'preserve_gateway_route_and_opt_out_policy_trace',
    'reject_gateway_sends_provider_callbacks_mutation_and_persistence',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.announcement_ack_evidence.runtime_evaluated'],
  external_dependencies: [
    {
      target: '6A.11',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-004'],
      reason: 'Acknowledgement evidence is tied to an outbound announcement delivered through the Communication Gateway.',
    },
  ],
  forbidden_behaviors: [
    'provider_callback_execution',
    'gateway_send_execution',
    'acknowledgement_mutation_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
