export const calendarOriginEventRefModuleManifest = {
  seed_id: 'seed_6c_092_calendar_origin_event_ref',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.calendar_origin_event_ref',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Calendar origin event refs from HR/tasks/events/LMS later',
  proposed_model_name: 'Phase6CCalendarOriginEventRef',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-010', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'calendar_event_ref',
    'source_record_ref',
    'origin_system',
    'origin_event_id',
    'origin_entity_ref',
    'correlation_id',
    'source_event_payload_hash',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'normalize_calendar_origin_event_reference',
    'accept_hr_task_event_lms_origins_as_event_refs_only',
    'derive_stable_origin_reference_id',
    'reject_cross_module_writes_queries_provider_sync_and_persistence',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.calendar_origin_event_ref.runtime_evaluated'],
  allowed_origin_systems: ['HR', 'TASKS', 'EVENTS', 'LMS'],
  forbidden_behaviors: [
    'calendar_write_execution',
    'origin_mutation_execution',
    'direct_cross_module_query',
    'provider_sync_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
