export const calendarProviderSyncBoundaryModuleManifest = {
  seed_id: 'seed_6c_084_calendar_provider_sync_boundary',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.calendar_provider_sync_boundary',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Google/Outlook adapter boundary only',
  proposed_model_name: 'Phase6CCalendarProviderSyncBoundary',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  adapter_boundary_only: true,
  provider_neutral_only: true,
  decision_refs: ['6C-CAL-002', '6C-CAL-001', '6C-GLOBAL-012', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'boundary_ref',
    'provider',
    'direction',
    'requested_scopes',
    'provider_neutral_calendar_entry_ref',
    'boundary_envelope',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.calendar_provider_sync_boundary.runtime_evaluated'],
  evidence_artifacts: [
    'calendar_provider_sync_boundary_runtime_receipt',
    'calendar_provider_sync_boundary_validation_result',
    'calendar_provider_sync_boundary_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'raw_provider_credential_capture',
    'provider_sdk_call',
    'sync_execution',
    'webhook_registration',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
