export const mandatoryNoticeClassificationModuleManifest = {
  seed_id: 'seed_6c_089_mandatory_notice_classification',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.mandatory_notice_classification',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Mandatory vs opt-out notice classification',
  proposed_model_name: 'Phase6CMandatoryNoticeClassification',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-007', '6C-CAL-006', '6C-GLOBAL-013', '6C-ADL-008', '6C-ADL-009'],
  adl_refs: ['ADL-004'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'notice_id',
    'source_record_ref',
    'notice_purpose',
    'classification',
    'mandatory_basis',
    'mandatory_source_authority_ref',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'classify_notice_as_mandatory_or_opt_out_eligible',
    'require_cited_basis_for_mandatory_opt_out_exemption',
    'keep_mandatory_notices_gateway_routed',
    'mark_non_mandatory_notices_for_opt_out_enforcement',
    'send_uncited_or_conflicting_mandatory_claims_to_manual_review',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.mandatory_notice_classification.runtime_evaluated'],
  downstream_surfaces: ['phase_6c.workspace_calendar_meetings_rooms_announcements.announcement_gateway'],
  forbidden_behaviors: [
    'direct_provider_send',
    'gateway_bypass',
    'manual_opt_out_bypass',
    'content_only_mandatory_inference',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
