export const mandatoryNoticeClassificationModuleManifest = {
  seed_id: "seed_6c_089_mandatory_notice_classification",
  component_id: "6C.07",
  component_slug: "workspace_calendar_meetings_rooms_announcements",
  module_key: "phase-6c.workspace-calendar-meetings-rooms-announcements",
  capability_surface: "phase_6c.workspace_calendar_meetings_rooms_announcements.mandatory_notice_classification",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Mandatory vs opt-out notice classification",
  proposed_model_name: "Phase6CMandatoryNoticeClassification",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-CAL-007"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
