export const meetingAttendanceEvidenceModuleManifest = {
  seed_id: 'seed_6c_093_meeting_attendance_evidence',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.meeting_attendance_evidence',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Meeting attendance Workspace evidence',
  proposed_model_name: 'Phase6CMeetingAttendanceEvidence',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-011', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'meeting_ref',
    'calendar_event_ref',
    'source_record_ref',
    'participant_attendance',
    'correlation_id',
    'source_event_payload_hash',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'normalize_meeting_attendance_evidence',
    'summarize_participant_attendance_counts',
    'derive_workspace_evidence_reference_entries',
    'reject_workspace_writes_provider_fetches_and_attendance_mutation',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.meeting_attendance_evidence.runtime_evaluated'],
  forbidden_behaviors: [
    'workspace_write_execution',
    'provider_fetch_execution',
    'attendance_mutation_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
