export const providerNeutralCalendarEntryModuleManifest = {
  seed_id: 'seed_6c_083_provider_neutral_calendar_entry',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.provider_neutral_calendar_entry',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Provider-neutral calendar entry runtime',
  proposed_model_name: 'Phase6CProviderNeutralCalendarEntry',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  provider_neutral_runtime_first: true,
  adapter_boundary_only: true,
  decision_refs: ['6C-CAL-001', '6C-CAL-002', '6C-WORK-TASK-015', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'calendar_entry_ref',
    'source_type',
    'source_ref',
    'provider_neutral_payload',
    'entry_uid',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.provider_neutral_calendar_entry.runtime_evaluated'],
  evidence_artifacts: [
    'provider_neutral_calendar_entry_runtime_receipt',
    'provider_neutral_calendar_entry_validation_result',
    'provider_neutral_calendar_entry_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'google_calendar_sync',
    'outlook_calendar_sync',
    'provider_credential_access',
    'direct_provider_mutation',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
