export const recurringEventRuleModuleManifest = {
  seed_id: 'seed_6c_091_recurring_event_rule',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.recurring_event_rule',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Recurring calendar event rules',
  proposed_model_name: 'Phase6CRecurringEventRule',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-009'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'rule_id',
    'source_record_ref',
    'frequency',
    'interval',
    'start_date',
    'end_date',
    'occurrence_count',
    'days_of_week',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'validate_recurring_calendar_event_rule',
    'normalize_daily_weekly_monthly_recurrence',
    'generate_bounded_seed_local_occurrence_preview',
    'reject_calendar_writes_provider_sync_and_persistence',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.recurring_event_rule.runtime_evaluated'],
  forbidden_behaviors: [
    'calendar_write_execution',
    'provider_sync_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
