export const reminderQuietHoursModuleManifest = {
  seed_id: 'seed_6c_090_reminder_quiet_hours',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.reminder_quiet_hours',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Reminder quiet-hour enforcement',
  proposed_model_name: 'Phase6CReminderQuietHours',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-008', '6C-GLOBAL-013', '6C-ADL-008'],
  adl_refs: ['ADL-004'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'reminder_id',
    'source_record_ref',
    'recipient_user_id',
    'scheduled_local_day',
    'scheduled_local_time',
    'quiet_hour_windows',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'evaluate_reminder_against_configurable_quiet_hours',
    'defer_reminders_until_quiet_hours_end',
    'preserve_communication_gateway_route_requirement',
    'reject_direct_provider_or_quiet_hour_override_requests',
    'produce_seed_local_reminder_quiet_hours_receipt',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.reminder_quiet_hours.runtime_evaluated'],
  external_dependencies: [
    {
      target: '6A.11',
      basis: 'adl_hard_rule',
      adl_refs: ['ADL-004'],
      reason: 'Reminder delivery remains an outbound communication and must route through the Communication Gateway.',
    },
  ],
  forbidden_behaviors: [
    'direct_provider_send',
    'gateway_bypass',
    'quiet_hours_override_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
