export const resourceCapacityEquipmentModuleManifest = {
  seed_id: 'seed_6c_087_resource_capacity_equipment',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.resource_capacity_equipment',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Room/resource capacity and equipment metadata',
  proposed_model_name: 'Phase6CResourceCapacityEquipment',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  capacity_metadata_required_for_rooms: true,
  equipment_metadata_supported: true,
  decision_refs: ['6C-CAL-005', '6C-CAL-004', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'resource_ref',
    'resource_type',
    'display_name',
    'status',
    'capacity',
    'equipment',
    'accessibility_features',
    'metadata_tags',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.resource_capacity_equipment.runtime_evaluated'],
  evidence_artifacts: [
    'resource_capacity_equipment_runtime_receipt',
    'resource_capacity_equipment_validation_result',
    'resource_capacity_equipment_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'booking_write_execution',
    'calendar_write_execution',
    'inventory_mutation_execution',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
