export const roomBookingConflictModuleManifest = {
  seed_id: 'seed_6c_086_room_booking_conflict',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.room_booking_conflict',
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: 'Room/resource booking conflict detection',
  proposed_model_name: 'Phase6CRoomBookingConflict',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  conflict_detection_required: true,
  capacity_metadata_supported: true,
  decision_refs: ['6C-CAL-004', '6C-CAL-005', '6C-GLOBAL-018'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'candidate_booking',
    'requested_resources',
    'existing_bookings',
    'conflict_findings',
    'runtime_evidence_digest',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.room_booking_conflict.runtime_evaluated'],
  evidence_artifacts: [
    'room_booking_conflict_runtime_receipt',
    'room_booking_conflict_validation_result',
    'room_booking_conflict_forbidden_behavior_rejection_evidence',
  ],
  forbidden_behaviors: [
    'booking_write_execution',
    'calendar_write_execution',
    'provider_sync_execution',
    'persistence_execution',
    'cross_phase_write',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'ticket_flag_flip',
  ],
} as const;
