export const syncFailureDegradationModuleManifest = {
  seed_id: 'seed_6c_094_sync_failure_degradation',
  component_id: '6C.07',
  component_slug: 'workspace_calendar_meetings_rooms_announcements',
  module_key: 'phase-6c.workspace-calendar-meetings-rooms-announcements',
  capability_surface: 'phase_6c.workspace_calendar_meetings_rooms_announcements.sync_failure_degradation',
  source_system: 'PHASE_6C_FFET_RUNTIME',
  objective: 'Calendar sync failure degradation',
  proposed_model_name: 'Phase6CSyncFailureDegradation',
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ['6C-CAL-012'],
  owned_data: [
    'organization_id',
    'service_manifest_contract_id',
    'sync_job_ref',
    'source_record_ref',
    'sync_surface',
    'failure_class',
    'attempt_count',
    'provider_correlation_id',
    'runtime_evidence_digest',
  ],
  runtime_behaviors: [
    'classify_calendar_sync_failure_degradation',
    'compute_retry_or_local_only_fallback_decision',
    'preserve_local_calendar_readmodel_fallback',
    'reject_provider_retry_mutation_credential_access_and_persistence',
  ],
  emitted_events: ['phase_6c.workspace_calendar_meetings_rooms_announcements.sync_failure_degradation.runtime_evaluated'],
  forbidden_behaviors: [
    'provider_retry_execution',
    'provider_mutation_execution',
    'credential_access_execution',
    'runtime_adapter_execution',
    'schema_mutation',
    'frontend_screen',
    'shared_app_module_wiring',
    'ticket_flag_flip',
  ],
} as const;
