export const crmReportingDefinitionsModuleManifest = {
  seed_id: 'seed_6b_08_crm_reporting_definitions',
  component_id: '6B.08',
  capability_surface: 'crm_scoring_reporting.crm_reporting_definitions',
  source_system: 'CRM_SCORING_REPORTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  report_definitions_configurable: true,
  pipeline_stage_model_required: true,
  whatsapp_template_management_required: true,
  optimization_fact_store_required: true,
  owned_data: [
    'report_definition_id',
    'report_name',
    'pipeline_stage_model_ref',
    'whatsapp_template_management_ref',
    'optimization_fact_store_ref',
    'lifecycle_status',
    'metrics',
    'filters',
    'sorts',
  ],
  forbidden_behaviors: [
    'query_execution',
    'raw_sql_execution',
    'frontend_rendering',
    'schema_mutation',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
