export const crmComplianceViewsModuleManifest = {
  seed_id: 'seed_6b_08_crm_compliance_views',
  component_id: '6B.08',
  capability_surface: 'crm_scoring_reporting.crm_compliance_views',
  source_system: 'CRM_SCORING_REPORTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  compliance_views_configurable: true,
  pipeline_stage_model_required: true,
  whatsapp_template_management_required: true,
  optimization_fact_store_required: true,
  owned_data: [
    'compliance_view_id',
    'view_name',
    'audience',
    'pipeline_stage_model_ref',
    'whatsapp_template_management_ref',
    'optimization_fact_store_ref',
    'lifecycle_status',
    'visible_field_refs',
    'prohibited_field_refs',
    'evidence_sources',
  ],
  forbidden_behaviors: [
    'data_query_execution',
    'export_execution',
    'frontend_rendering',
    'schema_mutation',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
