export const followUpTaskCadenceModuleManifest = {
  seed_id: 'seed_6b_08_follow_up_task_cadence',
  component_id: '6B.08',
  capability_surface: 'crm_scoring_reporting.follow_up_task_cadence',
  source_system: 'CRM_SCORING_REPORTING',
  activation_lifecycle_required: true,
  tenant_service: true,
  cadence_rules_configurable: true,
  pipeline_stage_model_required: true,
  whatsapp_template_management_required: true,
  optimization_fact_store_required: true,
  owned_data: [
    'cadence_id',
    'lead_record_ref',
    'pipeline_stage_model_ref',
    'whatsapp_template_management_ref',
    'optimization_fact_store_ref',
    'anchor_at',
    'lifecycle_status',
    'cadence_steps',
    'planned_tasks',
  ],
  forbidden_behaviors: [
    'scheduler_execution',
    'communication_send',
    'hardcoded_cadence_timing',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
