export const leadScoringEngineModuleManifest = {
  seed_id: 'seed_6b_08_lead_scoring_engine',
  component_id: '6B.08',
  capability_surface: 'crm_scoring_reporting.lead_scoring_engine',
  source_system: 'CRM_SCORING_REPORTING',
  activation_lifecycle_required: true,
  core_microservice: true,
  scoring_rules_configurable: true,
  pipeline_stage_model_required: true,
  whatsapp_template_management_required: true,
  optimization_fact_store_required: true,
  owned_data: [
    'scoring_run_id',
    'lead_record_ref',
    'pipeline_stage_model_ref',
    'whatsapp_template_management_ref',
    'optimization_fact_store_ref',
    'scoring_rules',
    'facts',
    'score_band',
    'rule_results',
  ],
  forbidden_behaviors: [
    'hardcoded_scoring_weights',
    'ai_generated_score',
    'schema_mutation',
    'frontend_screen',
    'shared_scaffold_mutation',
    'irreversible_customer_action',
  ],
} as const;
