import { ModuleManifestSchema, type ModuleManifest } from "./module-manifest.schema.js";

export const leadDeskCoreModuleManifest: ModuleManifest = ModuleManifestSchema.parse({
  module_key: "lead.desk",
  display_name: "Lead Desk Core",
  module_type: "standard",
  version: "0.1.0",
  owner: "admissions",
  min_platform_version: "0.1.0",
  dependencies: [
    {
      module_key: "core.access",
      min_version: "0.1.0",
    },
    {
      module_key: "engagement.gateway",
      min_version: "0.1.0",
    },
  ],
  optional_dependencies: [],
  capabilities: [
    {
      key: "lead.intake.create",
      description: "Create a lead intake record.",
      module_key: "lead.desk",
      risk_level: "high",
      requires_permission: true,
      requires_reauth: false,
      requires_audit: true,
      gatekeeper_required: true,
      approval_chain_required: false,
      input_schema: "lead.desk.lead.create.input",
      output_schema: "lead.desk.lead.create.output",
    },
    {
      key: "lead.inbox.view",
      description: "View lead inbox records.",
      module_key: "lead.desk",
      risk_level: "low",
      requires_permission: true,
      requires_reauth: false,
      requires_audit: false,
      gatekeeper_required: false,
      approval_chain_required: false,
      input_schema: "lead.desk.lead.list.input",
      output_schema: "lead.desk.lead.list.output",
    },
    {
      key: "lead.detail.view",
      description: "View lead detail.",
      module_key: "lead.desk",
      risk_level: "low",
      requires_permission: true,
      requires_reauth: false,
      requires_audit: false,
      gatekeeper_required: false,
      approval_chain_required: false,
      input_schema: "lead.desk.lead.detail.input",
      output_schema: "lead.desk.lead.detail.output",
    },
    {
      key: "lead.status.update",
      description: "Update lead status.",
      module_key: "lead.desk",
      risk_level: "medium",
      requires_permission: true,
      requires_reauth: false,
      requires_audit: true,
      gatekeeper_required: true,
      approval_chain_required: false,
      input_schema: "lead.desk.lead.status.update.input",
      output_schema: "lead.desk.lead.status.update.output",
    },
    {
      key: "lead.inbox.assign",
      description: "Assign lead ownership.",
      module_key: "lead.desk",
      risk_level: "medium",
      requires_permission: true,
      requires_reauth: false,
      requires_audit: true,
      gatekeeper_required: true,
      approval_chain_required: false,
      input_schema: "lead.desk.lead.assign.input",
      output_schema: "lead.desk.lead.assign.output",
    },
  ],
  capabilities_consumed: [
    {
      capability_key: "engagement.gateway.request.create",
      provider_module_key: "engagement.gateway",
      required: true,
      min_version: "0.1.0",
    },
  ],
  permissions: [
    {
      key: "lead.intake.create",
      label: "Create leads",
      module_key: "lead.desk",
      description: "Allow creating lead intake records.",
      allowed_scope_types: ["organization", "own_unit"],
    },
    {
      key: "lead.inbox.view",
      label: "View lead inbox",
      module_key: "lead.desk",
      description: "Allow viewing lead inbox records.",
      allowed_scope_types: ["organization", "own_unit", "assigned_records"],
    },
    {
      key: "lead.detail.view",
      label: "View lead detail",
      module_key: "lead.desk",
      description: "Allow opening lead detail records.",
      allowed_scope_types: ["organization", "own_unit", "assigned_records"],
    },
    {
      key: "lead.status.update",
      label: "Update lead status",
      module_key: "lead.desk",
      description: "Allow updating lead status.",
      allowed_scope_types: ["organization", "own_unit", "assigned_records"],
    },
    {
      key: "lead.inbox.assign",
      label: "Assign leads",
      module_key: "lead.desk",
      description: "Allow assigning lead ownership.",
      allowed_scope_types: ["organization", "own_unit"],
    },
  ],
  api_routes: [
    {
      method: "POST",
      path: "/api/lead-desk/organizations/:organization_id/leads",
      capability_key: "lead.intake.create",
      auth_required: true,
      public_route: false,
      rate_limited: true,
      input_schema: "lead.desk.lead.create.input",
      output_schema: "lead.desk.lead.create.output",
    },
    {
      method: "GET",
      path: "/api/lead-desk/organizations/:organization_id/leads",
      capability_key: "lead.inbox.view",
      auth_required: true,
      public_route: false,
      rate_limited: true,
      input_schema: "lead.desk.lead.list.input",
      output_schema: "lead.desk.lead.list.output",
    },
    {
      method: "GET",
      path: "/api/lead-desk/organizations/:organization_id/leads/:lead_id",
      capability_key: "lead.detail.view",
      auth_required: true,
      public_route: false,
      rate_limited: true,
      input_schema: "lead.desk.lead.detail.input",
      output_schema: "lead.desk.lead.detail.output",
    },
    {
      method: "PATCH",
      path: "/api/lead-desk/organizations/:organization_id/leads/:lead_id/status",
      capability_key: "lead.status.update",
      auth_required: true,
      public_route: false,
      rate_limited: true,
      input_schema: "lead.desk.lead.status.update.input",
      output_schema: "lead.desk.lead.status.update.output",
    },
    {
      method: "PATCH",
      path: "/api/lead-desk/organizations/:organization_id/leads/:lead_id/assignment",
      capability_key: "lead.inbox.assign",
      auth_required: true,
      public_route: false,
      rate_limited: true,
      input_schema: "lead.desk.lead.assign.input",
      output_schema: "lead.desk.lead.assign.output",
    },
  ],
  events_emitted: [
    {
      event_type: "lead.desk.lead.created",
      version: "0.1.0",
      source_module: "lead.desk",
      schema: "lead.desk.lead.created.event",
      delivery_mode: "transactional_outbox",
      retry_policy: {
        strategy: "none",
        max_attempts: 0,
        initial_delay_ms: 0,
      },
      idempotency_key_fields: ["lead_id"],
    },
    {
      event_type: "lead.desk.lead.status.updated",
      version: "0.1.0",
      source_module: "lead.desk",
      schema: "lead.desk.lead.status.updated.event",
      delivery_mode: "transactional_outbox",
      retry_policy: {
        strategy: "none",
        max_attempts: 0,
        initial_delay_ms: 0,
      },
      idempotency_key_fields: ["lead_id"],
    },
    {
      event_type: "lead.desk.lead.assigned",
      version: "0.1.0",
      source_module: "lead.desk",
      schema: "lead.desk.lead.assigned.event",
      delivery_mode: "transactional_outbox",
      retry_policy: {
        strategy: "none",
        max_attempts: 0,
        initial_delay_ms: 0,
      },
      idempotency_key_fields: ["lead_id", "assigned_user_id"],
    },
  ],
  events_consumed: [],
  schemas: [
    { key: "lead.desk.lead.create.input", version: "0.1.0", description: "Lead create input." },
    { key: "lead.desk.lead.create.output", version: "0.1.0", description: "Lead create output." },
    { key: "lead.desk.lead.list.input", version: "0.1.0", description: "Lead list input." },
    { key: "lead.desk.lead.list.output", version: "0.1.0", description: "Lead list output." },
    { key: "lead.desk.lead.detail.input", version: "0.1.0", description: "Lead detail input." },
    { key: "lead.desk.lead.detail.output", version: "0.1.0", description: "Lead detail output." },
    { key: "lead.desk.lead.status.update.input", version: "0.1.0", description: "Lead status update input." },
    { key: "lead.desk.lead.status.update.output", version: "0.1.0", description: "Lead status update output." },
    { key: "lead.desk.lead.assign.input", version: "0.1.0", description: "Lead assignment input." },
    { key: "lead.desk.lead.assign.output", version: "0.1.0", description: "Lead assignment output." },
    { key: "lead.desk.lead.created.event", version: "0.1.0", description: "Lead created event." },
    { key: "lead.desk.lead.status.updated.event", version: "0.1.0", description: "Lead status updated event." },
    { key: "lead.desk.lead.assigned.event", version: "0.1.0", description: "Lead assigned event." },
  ],
  migrations: [],
  settings: [],
  menu_entries: [],
  dashboard_widgets: [],
  gatekeeper_hooks: [
    {
      key: "lead.desk.create.gatekeeper",
      capability_key: "lead.intake.create",
      description: "Gatekeeper preflight for lead creation.",
      required: true,
    },
    {
      key: "lead.desk.status.update.gatekeeper",
      capability_key: "lead.status.update",
      description: "Gatekeeper preflight for status updates.",
      required: true,
    },
    {
      key: "lead.desk.assignment.gatekeeper",
      capability_key: "lead.inbox.assign",
      description: "Gatekeeper preflight for lead assignment updates.",
      required: true,
    },
  ],
  audit_hooks: [
    {
      key: "lead.desk.lead.created.audit",
      event_type: "lead.desk.lead.created",
      description: "Audit hook for lead creation.",
      required: true,
    },
    {
      key: "lead.desk.lead.status.updated.audit",
      event_type: "lead.desk.lead.status.updated",
      description: "Audit hook for lead status updates.",
      required: true,
    },
    {
      key: "lead.desk.lead.assigned.audit",
      event_type: "lead.desk.lead.assigned",
      description: "Audit hook for lead assignment updates.",
      required: true,
    },
  ],
  health_checks: [],
  degraded_mode_behavior: {
    mode: "limited",
    description: "Lead mutations can be restricted while reads remain available.",
    disabled_capabilities: ["lead.intake.create", "lead.status.update", "lead.inbox.assign"],
  },
  disable_behavior: {
    description: "Disabling Lead Desk Core blocks lead intake and assignment operations.",
    blocks_dependent_modules: false,
    data_retention_required: true,
  },
  data_ownership: {
    owner_module_key: "lead.desk",
    tenant_scoped: true,
    entity_refs: [],
    retention_policy: "Lead retention follows admissions policy and platform audit/outbox policy.",
    sensitive_data: true,
  },
});
