export const employeeNumberPolicyModuleManifest = {
  seed_id: "seed_6c_002_employee_number_policy",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_number_policy",
  source_system: 'PHASE_6C_GATE_4_RUNTIME_IMPLEMENTATION',
  objective: "Stable UUID plus configurable employee display number policy",
  proposed_model_name: "Phase6CEmployeeNumberPolicy",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-EMP-001"],
  dependency_refs: ["seed_6a_service_manifest_contract", "seed_6c_001_employee_person_extension"],
  owned_data: ["organization_id", "service_manifest_contract_id", "stable_employee_uuid", "employee_person_extension_ref", "display_employee_number", "policy_config", "source_record_ref", "control_metadata", "employee_number_policy_evidence_digest"],
  forbidden_behaviors: ["hardcoded_employee_number", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
