export const employeePersonExtensionModuleManifest = {
  seed_id: "seed_6c_001_employee_person_extension",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_person_extension",
  source_system: 'PHASE_6C_GATE_4_RUNTIME_IMPLEMENTATION',
  objective: "Employee role extension linked to core Person",
  proposed_model_name: "Phase6CEmployeePersonExtension",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-EMP-006", "6C-SCHEMA-006", "6C-NON-007"],
  dependency_refs: ["seed_6a_service_manifest_contract", "6A.05", "6A.06"],
  owned_data: ["organization_id", "service_manifest_contract_id", "person_identity_graph_ref", "employee_record_ref", "employee_number", "extension_status", "effective_at", "source_record_ref", "control_metadata", "employee_person_extension_evidence_digest"],
  forbidden_behaviors: ["phase_6a_mutation", "phase_6b_mutation", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
