export const employeeLifecycleStatusHistoryModuleManifest = {
  seed_id: "seed_6c_008_employee_lifecycle_status_history",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_lifecycle_status_history",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Minimal hard lifecycle anchors and configurable status labels",
  proposed_model_name: "Phase6CEmployeeLifecycleStatusHistory",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  hard_lifecycle_anchors: ["active", "inactive", "terminated"],
  configurable_status_labels: true,
  decision_refs: ["6C-HR-EMP-008", "6C-SCHEMA-006", "6C-NON-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "status_labels",
    "status_changes",
    "current_status_by_employee",
    "status_counts",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "hard_anchor_mutation",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
