export const employmentContractRecordModuleManifest = {
  seed_id: "seed_6c_005_employment_contract_record",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employment_contract_record",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Configurable employment contract records",
  proposed_model_name: "Phase6CEmploymentContractRecord",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-EMP-007", "6C-SCHEMA-006", "6C-NON-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "contracts",
    "contract_counts",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
