export const employeeCreatedEventModuleManifest = {
  seed_id: "seed_6c_010_employee_created_event",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_created_event",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Employee creation evidence/event for Workspace and payroll foundation",
  proposed_model_name: "Phase6CEmployeeCreatedEvent",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  workspace_provisioning_allowed: false,
  payroll_record_creation_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-EMP-015", "6C-SCHEMA-006", "6C-NON-007", "6C-GLOBAL-018"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "employee_record_ref",
    "person_identity_anchor_id",
    "employee_number_ref",
    "event_envelopes",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "workspace_provisioning",
    "payroll_record_creation",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
