export const employeeSensitiveFieldRedactionModuleManifest = {
  seed_id: "seed_6c_009_employee_sensitive_field_redaction",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_sensitive_field_redaction",
  source_system: 'PHASE_6C_RUNTIME_FFET',
  objective: "Sensitive HR field redaction and support-window policy",
  proposed_model_name: "Phase6CEmployeeSensitiveFieldRedaction",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  sensitive_field_set: ["compensation", "national_id", "bank", "health", "emergency_contact", "performance", "disciplinary"],
  support_window_required_for_workspace_admin_private_access: true,
  decision_refs: ["6C-HR-EMP-010", "6C-SEC-005", "6C-SEC-006", "6C-SCHEMA-006", "6C-NON-007"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "redacted_records",
    "redaction_counts",
    "support_window_ref",
    "control_metadata",
    "runtime_evidence_digest",
  ],
  forbidden_behaviors: [
    "support_window_bypass",
    "unrestricted_sensitive_export",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
