export const employeeSensitiveFieldRedactionModuleManifest = {
  seed_id: "seed_6c_009_employee_sensitive_field_redaction",
  component_id: "6C.01",
  component_slug: "hr_employee_records_and_organisation_structure",
  module_key: "phase-6c.hr-employee-records-and-organisation-structure",
  capability_surface: "phase_6c.hr_employee_records_and_organisation_structure.employee_sensitive_field_redaction",
  source_system: 'PHASE_6C_SCHEMA_CONTROL_BASELINE',
  objective: "Sensitive HR field redaction and support-window policy",
  proposed_model_name: "Phase6CEmployeeSensitiveFieldRedaction",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: false,
  business_behavior_allowed: false,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-HR-EMP-010"],
  owned_data: ["organization_id", "service_manifest_contract_id", "source_seed_id", "source_record_ref", "control_metadata", "scaffold_evidence_digest"],
  forbidden_behaviors: ["capability_execution", "business_rule_execution", "runtime_adapter_execution", "schema_mutation", "frontend_screen", "shared_scaffold_mutation", "ticket_flag_flip"],
} as const;
