export const crossModuleChannelRefModuleManifest = {
  seed_id: "seed_6c_066_cross_module_channel_ref",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.cross_module_channel_ref",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Cross-module channels through registered refs",
  proposed_model_name: "Phase6CCrossModuleChannelRef",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-012", "6C-GLOBAL-018"],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.cross_module_channel_ref.evaluated"],
  required_inputs: ["organization_id", "workspace_ref", "channel_ref", "registered_refs", "requested_refs"],
  provided_outputs: [
    "normalized_refs",
    "accepted_ref_count",
    "rejected_ref_count",
    "review_reasons",
    "blockers",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_behaviors: [
    "mutate_other_module_record",
    "direct_cross_module_query",
    "runtime_adapter_execution",
    "event_bus_dispatch",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/cross_module_channel_ref.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
