export const membershipPolicyModuleManifest = {
  seed_id: "seed_6c_064_membership_policy",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.membership_policy",
  source_system: "PHASE_6C_RUNTIME_FFET",
  contract_namespace: "esbla.phase_6c.workspace_messaging_and_collaboration",
  contract_export_subpath: "./phase-6c-workspace-membership-policy-module-manifest",
  contract_change_id: "S2-CC-001",
  package_namespace_compatibility: "workspace_package_name_compatibility_locked",
  objective: "Membership policy from Access Core roles and employee teams",
  proposed_model_name: "Phase6CMembershipPolicy",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-010", "6C-GLOBAL-018"],
  reference_inputs: ["access_core_role_refs", "employee_team_refs", "employee_status"],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.membership_policy.evaluated"],
  required_inputs: ["organization_id", "workspace_ref", "resource_ref", "policy", "candidates"],
  provided_outputs: [
    "evaluations",
    "grant_count",
    "deny_count",
    "review_count",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_behaviors: [
    "mutate_access_core_roles",
    "mutate_employee_teams",
    "mutate_workspace_membership",
    "bypass_gatekeeper",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "event_bus_dispatch",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/membership_policy.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
