export const mentionNotificationEvidenceModuleManifest = {
  seed_id: "seed_6c_063_mention_notification_evidence",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.mention_notification_evidence",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Mention notification evidence",
  proposed_model_name: "Phase6CMentionNotificationEvidence",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-008", "6C-GLOBAL-013", "6C-ADL-008"],
  adl_refs: ["ADL-004"],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.mention_notification_evidence.recorded"],
  required_inputs: [
    "organization_id",
    "workspace_ref",
    "conversation_ref",
    "message_ref",
    "notification_ref",
    "mentions",
  ],
  provided_outputs: [
    "records",
    "gateway_prepared_count",
    "suppressed_count",
    "review_count",
    "decision",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_behaviors: [
    "send_message_to_provider",
    "provider_adapter_execution",
    "gateway_bypass",
    "global_opt_out_override",
    "event_bus_dispatch",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/mention_notification_evidence.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
