export const messageEditHistoryModuleManifest = {
  seed_id: "seed_6c_059_message_edit_history",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.message_edit_history",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Immutable message edit history",
  proposed_model_name: "Phase6CMessageEditHistory",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-004", "6C-GLOBAL-018"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "conversation_ref",
    "message_ref",
    "edit_ref",
    "previous_body_hash",
    "new_body_hash",
    "edit_history_evidence_digest",
  ],
  emitted_events: ["phase_6c.workspace_messaging_and_collaboration.message_edit_history.evaluated"],
  evidence_artifacts: [
    "message_edit_history_runtime_receipt",
    "message_edit_history_validation_result",
    "message_edit_history_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "content_overwrite",
    "history_delete",
    "realtime_delivery_execution",
    "event_dispatch_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
