export const messageTombstoneStagedDeletionModuleManifest = {
  seed_id: "seed_6c_060_message_tombstone_staged_deletion",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.message_tombstone_staged_deletion",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Message tombstone and staged deletion",
  proposed_model_name: "Phase6CMessageTombstoneStagedDeletion",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-005", "6C-GLOBAL-018"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "conversation_ref",
    "message_ref",
    "tombstone_decision",
    "purge_not_before",
    "tombstone_evidence_digest",
  ],
  emitted_events: ["phase_6c.workspace_messaging_and_collaboration.message_tombstone_staged_deletion.evaluated"],
  evidence_artifacts: [
    "message_tombstone_staged_deletion_runtime_receipt",
    "message_tombstone_staged_deletion_validation_result",
    "message_tombstone_staged_deletion_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "tombstone_mutation",
    "physical_delete",
    "purge_execution",
    "event_dispatch_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
