export const PHASE_6C_MESSAGE_ATTACHMENT_FILE_REF_MODULE_MANIFEST = {
  seed_id: "seed_6c_061_message_attachment_file_ref",
  component_id: "6C.05",
  source_system: "PHASE_6C_RUNTIME_FFET",
  capability: "message_attachment_file_ref",
  capability_implementation_allowed: true,
  runtime_behavior_authorized: true,
  activation_dependency: "seed_6a_service_manifest_contract",
  cross_phase_dependency_model: "reference_only_existing_file_refs",
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.message_attachment_file_ref.evaluated"],
  decision_refs: ["6C-WORK-MSG-006", "6C-GLOBAL-018"],
  required_inputs: [
    "organization_id",
    "conversation_ref",
    "message_ref",
    "actor_user_ref",
    "attachments",
  ],
  provided_outputs: [
    "attachment_count",
    "total_byte_size",
    "prepared_attachments",
    "decision",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_runtime_behaviors: [
    "upload_file_blob",
    "mutate_phase_6a_file_ref",
    "mutate_phase_6b_record",
    "proxy_file_download",
    "send_notification",
    "dispatch_event_bus_message",
    "change_schema_or_registry",
    "flip_ticket_or_execution_flags",
    "wire_controller_or_frontend_route",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/message_attachment_file_ref.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
