export const moderationReportingModuleManifest = {
  seed_id: "seed_6c_068_moderation_reporting",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.moderation_reporting",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Workspace moderation/reporting",
  proposed_model_name: "Phase6CModerationReporting",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-014", "6C-GLOBAL-018"],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.moderation_reporting.evaluated"],
  required_inputs: ["organization_id", "workspace_ref", "report_ref", "reported_message_ref", "policy"],
  provided_outputs: [
    "decision",
    "escalation_required",
    "duplicate_risk",
    "review_reasons",
    "rejection_reasons",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_behaviors: [
    "remove_content",
    "perform_account_action",
    "send_notification",
    "bypass_gatekeeper",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "event_bus_dispatch",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/moderation_reporting.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
