export const privateChannelApprovalModuleManifest = {
  seed_id: "seed_6c_065_private_channel_approval",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.private_channel_approval",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Configurable private-channel approval",
  proposed_model_name: "Phase6CPrivateChannelApproval",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-011", "6C-GLOBAL-018"],
  configurable_policy_inputs: [
    "approval_mode",
    "allowed_requester_role_refs",
    "allowed_requester_team_refs",
    "required_approver_role_refs",
    "require_business_justification",
    "max_initial_member_count",
  ],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.private_channel_approval.evaluated"],
  required_inputs: ["organization_id", "workspace_ref", "requested_channel_ref", "policy", "requester_context"],
  provided_outputs: [
    "decision",
    "requester_policy_matched",
    "approver_policy_matched",
    "review_reasons",
    "deny_reasons",
    "evidence_artifacts",
    "deterministic_digest",
  ],
  forbidden_behaviors: [
    "create_private_channel",
    "mutate_workspace_membership",
    "send_approval_notification",
    "bypass_gatekeeper",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "event_bus_dispatch",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/private_channel_approval.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
