export const workspaceMessageSearchModuleManifest = {
  seed_id: "seed_6c_067_workspace_message_search",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.workspace_message_search",
  source_system: "PHASE_6C_RUNTIME_FFET",
  contract_namespace: "esbla.phase_6c.workspace_messaging_and_collaboration",
  contract_export_subpath: "./phase-6c-workspace-workspace-message-search-module-manifest",
  contract_change_id: "S2-CC-001",
  package_namespace_compatibility: "workspace_package_name_compatibility_locked",
  objective: "Workspace message search via 6A Search/File layer",
  proposed_model_name: "Phase6CWorkspaceMessageSearch",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-013", "6C-GLOBAL-018"],
  reference_inputs: ["search_layer_evidence_ref", "file_refs", "access_filter_ref"],
  owned_events: ["phase_6c.workspace_messaging_and_collaboration.workspace_message_search.evaluated"],
  required_inputs: ["organization_id", "workspace_ref", "query_text", "allowed_channel_refs", "records"],
  provided_outputs: ["results", "normalized_terms", "review_reasons", "evidence_artifacts", "deterministic_digest"],
  forbidden_behaviors: [
    "execute_external_search_runtime",
    "mutate_search_index",
    "mutate_file_layer",
    "direct_cross_module_query",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "event_bus_dispatch",
    "frontend_screen",
    "ticket_flag_flip",
  ],
  validation_commands: [
    "pnpm contracts:validate",
    "pnpm --filter @akti/api typecheck",
    "pnpm exec tsx apps/api/src/phase_6c/workspace_messaging_and_collaboration/workspace_message_search.service.test.ts",
    "pnpm --filter @akti/api test",
    "git diff --check",
  ],
} as const;
