export const workspaceChannelDmModuleManifest = {
  seed_id: "seed_6c_057_workspace_channel_dm",
  component_id: "6C.05",
  component_slug: "workspace_messaging_and_collaboration",
  module_key: "phase-6c.workspace-messaging-and-collaboration",
  capability_surface: "phase_6c.workspace_messaging_and_collaboration.workspace_channel_dm",
  source_system: "PHASE_6C_RUNTIME_FFET",
  objective: "Workspace channels and DMs",
  proposed_model_name: "Phase6CWorkspaceChannelDm",
  activation_lifecycle_required: true,
  tenant_service: true,
  organization_id_required: true,
  source_seed_trace_required: true,
  capability_implementation_allowed: true,
  business_behavior_allowed: true,
  runtime_adapter_allowed: false,
  decision_refs: ["6C-WORK-MSG-001", "6C-GLOBAL-018"],
  owned_data: [
    "organization_id",
    "service_manifest_contract_id",
    "source_seed_id",
    "source_record_ref",
    "conversation_ref",
    "conversation_kind",
    "visibility",
    "participant_refs",
    "channel_dm_evidence_digest",
  ],
  emitted_events: ["phase_6c.workspace_messaging_and_collaboration.workspace_channel_dm.evaluated"],
  evidence_artifacts: [
    "workspace_channel_dm_runtime_receipt",
    "workspace_channel_dm_validation_result",
    "workspace_channel_dm_forbidden_behavior_rejection_evidence",
  ],
  forbidden_behaviors: [
    "external_transport_execution",
    "notification_send_execution",
    "realtime_delivery_execution",
    "event_dispatch_execution",
    "schema_mutation",
    "phase_6a_mutation",
    "phase_6b_mutation",
    "runtime_adapter_execution",
    "frontend_screen",
    "shared_scaffold_mutation",
    "ticket_flag_flip",
  ],
} as const;
